### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by ajacksified** [Olivine-Labs/busted#239]
Create a debian package for `apt-get install busted`

**Comment by perusio** [comment]
Thanks for Busted. I created a Debian package for busted. You can find here: http://debian.perusio.net/ also created package for mediator_lua. All other packages are available in Debian.

**Comment by jpleau** [comment]
@perusio 

Hi !

We have uploaded a few Lua packages for busted in Debian (I see that you are already using most of them for your busted package!).

I have started some work on busted but I can see that you already have spent some time on this as well.. we should avoid duplicating efforts ! Would you be interested in helping with getting busted in Debian?

**Comment by perusio** [comment]
@jpleau sure. I have repos for all of the packages. Feel free to look around and pick what you find useful. I'm hardly a debian packaging expert but I'll be glad to help within my limited knowledge.

Thanks

**Comment by jpleau** [comment]
Hi

Package has been available in debian sid for a few weeks now: https://packages.debian.org/sid/lua-busted and also in ubuntu: http://packages.ubuntu.com/yakkety/lua-busted

I believe we can close this one :)
