### ISSUE TITLE
How can I run all test files of a specific directory?

### ISSUE THREAD

**Issue by EvandroLG** [Olivine-Labs/busted#334]
I would like to run a command like this: 
```shell
busted tests/*.lua
```
Is there any way?

Thanks

**Comment by iggyvolz** [comment]
If you're using bash (which is default on many non-Windows operating systems), you can run:
```bash
for file in tests/*.lua;do busted "$file";done
```

**Comment by EvandroLG** [comment]
nice, man! ;)
anyway, I think that should have a native way to run all tests!

**Comment by o-lim** [comment]
I believe what you are looking for is
```
$ busted -p ".*%.lua$" tests
```
This tells busted to run all `*.lua` files inside the tests directory.  By default busted will only run test files that have a `_spec` in the file name.  So you have to use the `-p` option to tell busted to match against all files.  This will also run all test files in any sub directory, so if that is not desired then you will have to use a script to avoid recursing into any sub directories.
