### ISSUE TITLE
Focus on a single test

### ISSUE THREAD

**Issue by PeqNP** [Olivine-Labs/busted#339]
I would love to be able to focus on a single `describe` or `it`. Cedar, a framework similar to this (also based on Rspec), allows you to prepend `describe` and `it` with an `f` to focus on a specific subset of tests while ignoring all of the others. The proposed changes would look something like this:

```lua
fit("it should do something", function() ...)
fdescribe("describing something", function() ...)
```

Thank you!

**Comment by mpeterv** [comment]
You could use tags for this, e.g.

```lua
it("it should do something #f", function() ...)
fdescribe("describing something", function() ...)
```

and invoke busted with `-t f` option.

**Comment by PeqNP** [comment]
:jaw drops: HOLY! That is _awesome_! Worked perfectly! Thank yo so much!

For anyone else who is curious, the command I ran was:

`$ busted -t f path/to/spec/my_spec.lua`
