### ISSUE TITLE
Provide more information to testEnd.

### ISSUE THREAD

**Issue by jszakmeister** [Olivine-Labs/busted#345]
I'd like to provide a bit more information than just the stack trace when something fails in the TAP and junit output.  Unfortunately, it seems the nice error message about the failure isn't present until the end of the suite.  Is there any chance this information can be added to the `element` node in the `testEnd` handlers?  I'd do this myself, but I'm still learning lua and busted is quite abstract.

**Comment by ajacksified** [comment]
https://github.com/Olivine-Labs/busted/pull/341 adds extra info to junit. Does that work for you? If it does, we can add better info to TAP.

**Comment by jszakmeister** [comment]
Yes it does.  It will be great having that for TAP!
