### ISSUE TITLE
Magic methods not setup after upgrading 2.0.rc3 to rc6 ("assert" etc)

### ISSUE THREAD

**Issue by blueyed** [Olivine-Labs/busted#346]
The busted tests in awesomeWM appear to fail after upgrading busted from 2.0.rc3 to rc6 (previously we suspected Lua 5.2 vs. Lua 5.1):

> spec/wibox/test_utils.lua:51: attempt to index global 'assert' (a function value)

(full build: https://travis-ci.org/blueyed/awesome/builds/51226266).

The "magic" setup of `assert`, `spy` etc does not appear to work as expected.

This appears to have regressed between 2.0.rc3-0 (which I was using locally, with Lua 5.2) and 2.0.rc6-0 (current).

The issue reference in awesomeWM is: https://github.com/awesomeWM/awesome/pull/139

**Comment by blueyed** [comment]
Bisected it to 7e98bade28b560000b755fca9e0e2b0bb1254694:

> commit 7e98bade28b560000b755fca9e0e2b0bb1254694
Author: Oscar Lim <olim@ucla.edu>
Date:   Wed Dec 31 01:52:26 2014 -0800

    Restrict luassert variables to busted environment
    
    The luassert variables assert/spy/mock/stub should only be visible
    inside a busted context. Other modules outside of busted should be free
    to reuse these variable names without interfering with the test
    environment. If other modules need to use luassert, they should
    explicitly `require` it. Otherwise, `assert` should default to the
    builtin Lua `assert`.

I guess that's a "won't fix" then.. :)

**Comment by blueyed** [comment]
To clarify things: it looks like the issue is, that `assert` is being used from a test/spec helper in this case: https://github.com/awesomeWM/awesome/blob/master/spec/wibox/test_utils.lua

    Error → spec/wibox/test_utils.lua @ 51
    ./spec/wibox/layout/align_spec.lua
    spec/wibox/test_utils.lua:51: attempt to index global 'assert' (a function value)
    Error → spec/wibox/test_utils.lua @ 51
    ./spec/wibox/layout/flex_spec.lua
    spec/wibox/test_utils.lua:51: attempt to index global 'assert' (a function value)
    Error → spec/wibox/test_utils.lua @ 51
    ./spec/wibox/layout/fixed_spec.lua
    spec/wibox/test_utils.lua:51: attempt to index global 'assert' (a function value)

I am reopening the issue, because I am not so sure anymore if this should or should not work - although the latter seems more likely.

**Comment by o-lim** [comment]
If you are using a helper module for your tests/specs then you should explicitly `require 'luassert'` in your helper module instead of relying on any kind of special setup by busted.  This also makes your test helpers more robust in the event you may need to reuse them in another testing framework.

The same would go for `luassert.spy`, `luassert.stub`, `luassert.mock`.
```lua
local assert = require 'luassert'
local spy = require 'luassert.spy'
local mock = require 'luassert.mock'
local stub = require 'luassert.stub'
```
or alternatively, with the latest updates in git
```lua
local assert = require 'busted'.assert
local spy = require 'busted'.spy
local mock = require 'busted'.mock
local stub = require 'busted'.stub
```

**Comment by jszakmeister** [comment]
My apologies, I just don't know enough about Lua and Busted, but does #335 affect things here?  It seems to be related.

**Comment by o-lim** [comment]
Yes, #335 enables the following:
```lua
local assert = require 'busted'.assert
local spy = require 'busted'.spy
local mock = require 'busted'.mock
local stub = require 'busted'.stub
```

**Comment by jszakmeister** [comment]
Thanks for clarifying @o-lim!

**Comment by ajacksified** [comment]
@jszakmeister - confirm that it works for you, and I'll close out. Thanks, @o-lim!

**Comment by blueyed** [comment]
@ajacksified 
FWIW, it "works" for me (the original reporter), as in "I understand what you did there".

**Comment by jszakmeister** [comment]
@ajacksified No worries.  I thought maybe the situation had changed with a recent commit and it would be magically available.  But I understand what's going on now.  Thanks!

**Comment by blueyed** [comment]
Closing the issue.  Thanks for all the clarification! :)
