### ISSUE TITLE
No global 'busted' as per readme?

### ISSUE THREAD

**Issue by kraftman** [Olivine-Labs/busted#357]
Hello!
Your page at http://olivinelabs.com/busted/ says: 
"Before Busted executes any tests it will define a global describe that can be used to expose private elements only in case of testing."

I've copied and pasted the example below it and run it but I get " attempt to get length of field '_private_element' (a nil value)" 
So it seems that the module isn't able to detect the global 'busted' variable?

**Comment by ajacksified** [comment]
Docs are a bit out of date; they're based on `rc4`, while we're on `rc6`. However, `local busted = require('busted')` should work. Run `busted --version`; what version are you on?

**Comment by kraftman** [comment]
Thanks. I'm on 2.0.rc6-0, I've tried that but "describe" still doesn't exist from within the module. For now I've done a workaround by setting _G.testing = true and then checking for that inside of the module but if there's a better way I'd rather use that.

Cheers!

**Comment by DorianGray** [comment]
We don't expose globals anymore. Feel free to implement your own method of checking to see if you're in a test context or not but we believe that it is a bad design decision. IMO it is always better to break your code into modules and test them individually than to only test at the high level interface level.

**Comment by DorianGray** [comment]
That being said, I believe you can get describe, etc, from requiring busted.init. You will need to make them global.

**Comment by o-lim** [comment]
@kraftman to get the behavior you want, I think what you are doing is the only way to achieve what you are looking for.  However, as @DorianGray said, having special test code in your modules is generally a bad design choice, and probably signifies that you need to break your module into smaller, more easily testable components.

**Comment by kraftman** [comment]
Thanks, I'll refactor my code to avoid it.
