### ISSUE TITLE
Improve documentation?

### ISSUE THREAD

**Issue by kraftman** [Olivine-Labs/busted#366]
Hello! 
I was wondering what the best way is to suggest corrections/enhancements to the documention? 

Cheers!

**Comment by naartjie** [comment]
@kraftman a PR will be welcome I'm sure.

I did one a while back and it was merged really quickly, so I encourage you to do the same :+1:

**Comment by kraftman** [comment]
Maybe I'm just being dumb but I can't find the source for the official docs, only the readme?

**Comment by naartjie** [comment]
The source for the website lives [here](https://github.com/Olivine-Labs/busted/tree/gh-pages).

**Comment by kraftman** [comment]
perfect, thanks!

**Comment by naartjie** [comment]
@kraftman I also offered to provide more examples of different assertions (as a way of learning busted), and I haven't done that yes :-/, so maybe let's work together on a PR? Let me know if you are keen.

**Comment by naartjie** [comment]
issue #198
