### ISSUE TITLE
Support for testing bytecode-compiled files?

### ISSUE THREAD

**Issue by hishamhm** [Olivine-Labs/busted#370]
I'd like to run some tests that require modules that are pre-compiled as bytecode — case in point: I'm writing modules in Typed Lua (`foo.tl`) and generating compiled bytecodes via tlc→luac, generating `foo.luac` — I added `"$PWD/?.luac;"` to my `LUA_PATH`. My test itself (the _spec file) is `.lua`.

This is the error I'm getting as a result:

```
✱
0 successes / 0 failures / 1 error / 0 pending : 0.004342 seconds

Error → ...am/luarocks/prefix-5.3/share/lua/5.3/moonscript/base.lua @ 65
./test/subprocess_spec.lua
...am/luarocks/prefix-5.3/share/lua/5.3/moonscript/base.lua:65: /Users/hisham/ac/dr/subprocess/subprocess.luac: Failed to parse:
 [1] >>    uaS
```

Apparently it is trying to load the required module via a MoonScript parser?...

**Comment by DorianGray** [comment]
Hmm, that's weird. Would you mind posting a test case that reproduces this issue?

**Comment by hishamhm** [comment]
```bash
> echo "print 'it works'; return {}" > mymodule.lua
> luac -o mymodule.luac mymodule.lua
> rm mymodule.lua
> echo 'require"mymodule"' > mytest_spec.lua
> LUA_PATH="./?.luac;$LUA_PATH" lua mytest_spec.lua
it works
> LUA_PATH="./?.luac;$LUA_PATH" busted mytest_spec.lua
✱
0 successes / 0 failures / 1 error / 0 pending : 0.007677 seconds

Error → ...am/luarocks/prefix-5.3/share/lua/5.3/moonscript/base.lua @ 65
./mytest_spec.lua
...am/luarocks/prefix-5.3/share/lua/5.3/moonscript/base.lua:65: ./mymodule.luac: Failed to parse:
 [1] >>    uaS
```

**Comment by mpeterv** [comment]
This appears to be an issue with moonscript loader as `LUA_PATH="./?.luac;$LUA_PATH" lua lmoonscript mytest_spec.lua` fails as well.

**Comment by mpeterv** [comment]
I sent a PR with a fix for moonscript(#176).

**Comment by DorianGray** [comment]
:+1:

**Comment by hishamhm** [comment]
@mpeterv Thank you!!
