### ISSUE TITLE
Create the output handler that prints at least test name immediately test is run

### ISSUE THREAD

**Issue by ZyX-I** [Olivine-Labs/busted#375]
All currently used output handlers assume that busted has a chance to shut down properly. This is not the case if the test is triggering lua(jit) bug, uses buggy C modules or has bug in code that uses luajit cffi. The only output handlers that give any information in this case are utfTerminal and plainTerminal, but counting `+` signs while you don’t know the order of execution of tests is not fun.

I suggest that there must be an output handler that prints *at least* information that is enough to identify the last test (which triggered a SEGV) *immediately*. Better if it will print all available information once it is available and have only a summary printed from `handler.suiteEnd`.

**Comment by tarruda** [comment]
Here's one that seems to do the trick:

```lua
return function(options, busted)
  local handler = require 'busted.outputHandlers.utfTerminal'(options, busted)

  handler.testStart = function(element, parent, status, debug)
    io.write('\n' .. handler.getFullName(element) .. ' ... ')
    io.flush()
  end

  busted.subscribe({ 'test', 'start' }, handler.testStart)

  return handler
end
```

I'm gonna add it to neovim deps until there's a native implementation in busted

**Comment by tarruda** [comment]
This variant also outputs the file name before the tests:

```lua
local ansicolors = require 'ansicolors'

return function(options, busted)
  local handler = require 'busted.outputHandlers.utfTerminal'(options, busted)

  handler.fileStart = function(name)
    io.write('\n' .. ansicolors('%{cyan}' .. name) .. ':')
  end

  handler.testStart = function(element, parent, status, debug)
    io.write('\n  ' .. handler.getFullName(element) .. ' ... ')
    io.flush()
  end

  busted.subscribe({ 'file', 'start' }, handler.fileStart)
  busted.subscribe({ 'test', 'start' }, handler.testStart)

  return handler
end
```

**Comment by thefosk** [comment]
+1

**Comment by tarruda** [comment]
This is already available in the latest version with the `gtest` output handler

**Comment by o-lim** [comment]
I believe PR #390 and #394 address this issue.
