### ISSUE TITLE
setup/teardown hooks are always executed even if no tests are going to be executed for a suite

### ISSUE THREAD

**Issue by tarruda** [Olivine-Labs/busted#377]
I frequently use the --tags option to focus on a single test while developing/debugging, but the setup hooks are always executed for all "describes", even when its children tests have been skipped by the tag filter.

Normally that wouldn't be an issue, but Neovim setup hooks are quite expensive, especially when running the tests with valgrind. Would it be possible to defer the setup/teardown hooks in such a way that they are only executed if the suite has at least one test that will be executed?

**Comment by tarruda** [comment]
FWIW I can meet this requirement by replacing `setup(cb)` calls by `before_each(once(cb))` where once is something like this:

```lua
function once(fn)
  return function()
    if fn then fn() end
    fn = nil
  end
end
```

But it would be better if busted supported lazy setup/teardown hooks natively.

**Comment by tarruda** [comment]
Is there a way to override the globals in each test file? If so I can replace the default setup/teardown functions with proxies that call `before_each(once(cb))` as suggested above

**Comment by o-lim** [comment]
I believe you can do
```lua
setup = function(cb)
  before_each(once(cb))
end
```
But I think would have to do this for each test file.

I guess you could add this line to beginning of each test file
```lua
local setup, teardown = require 'lazy_setup_teardown'
```
where `lazy_setup_teardown.lua` looks like
```lua
-- lazy_setup_teardown.lua
local before_each = require 'busted'.before_each
local after_each = require 'busted'.after_each

local function once(fn)
  return function()
    if fn then fn() end
    fn = nil
  end)
end

local lazy_setup =  function(cb)
  before_each(once(cb))
end)
local lazy_teardown =  function(cb)
  after_each(once(cb))
end)

return lazy_setup, lazy_teardown
```

**Comment by ajacksified** [comment]
We should look at the length of `it`s in the context and not execute setup/teardown if the length is 0.

**Comment by tarruda** [comment]
> But I think would have to do this for each test file.

That's what I was trying to avoid, especially if its something busted will support eventually

> We should look at the length of its in the context and not execute setup/teardown if the length is 0.

Sounds simple enough. I have looked into the part of the code which I assume is relevant to this issue(busted/execute.lua):

```lua
    for i = 1, runs do
      if i > 1 then
        busted.publish({ 'suite', 'reset' })
      end

      local root = busted.context.get()
      busted.publish({ 'suite', 'start' }, i, runs)
      if block.execAll('setup', root) then
        busted.execute()
      end
      block.dexecAll('teardown', root)
      busted.publish({ 'suite', 'end' }, i, runs)

      if busted.skipAll then
        break
      end
    end
```

Could you provide some guidance on how to get the it's length so setup/teardown can be avoided?

**Comment by o-lim** [comment]
>We should look at the length of its in the context and not execute setup/teardown if the length is 0.

I don't think this will work because this does not count the total number of `it` blocks nested in inner `describe` blocks.  For example:
```lua
describe('outer block', function()
  setup(function()
  ...
  end)

  describe('inner block1', function()
    it('inner test1', function()
    ...
    end)
  end)

  describe('inner block2', function()
    it('inner test2', function()
    ...
    end)
  end)
end)
```
The number of `it` blocks in the "outer block" is 0, but it has a total of 2 `it` blocks when you include the nested inner blocks.  So if you just look a the length of `it`'s in the describe context you would not run `setup` in the above use case.

In order to get the behavior you want, I think busted would have to implement something similar to the `once` function mentioned earlier.

**Comment by tarruda** [comment]
> In order to get the behavior you want, I think busted would have to implement something similar to the once function mentioned earlier.

The problem is that it wont work for the `teardown` hook which is executed after the suite.
