### ISSUE TITLE
how to mock a global function?

### ISSUE THREAD

**Issue by starius** [Olivine-Labs/busted#400]
I want to check that global function processEvent calls global function getEventType.

```lua
function processEvent(e)
  eventId = getEventType(e)
  if eventId == 3 then
    return 3
  else
    return 0
  end
end

describe("processEvent", function()
  it("calls getEventType with the event", function()
    function getEventType()
      return 3
    end
    stub(_G, "getEventType")
    processEvent(42)
    assert.stub(getEventType).was.called_with(42)
    getEventType:revert()
  end)
end)
```

Error message:
```
$ busted -v t_spec.lua 
✱
0 successes / 0 failures / 1 error / 0 pending : 0.000772 seconds

Error → ./t_spec.lua @ 11
processEvent calls getEventType with the event
/usr/local/share/lua/5.1/luassert/spy.lua:78: attempt to index a function value

stack traceback:
	./t_spec.lua:17: in function <./t_spec.lua:11>
```

This issue is based on [the question by mgyk](https://toster.ru/q/207629) (in Russian).

**Comment by o-lim** [comment]
It looks like your test is bad.  I tried the following and it works:
```lua
_G.getEventType = function (e)
  return 3
end
_G.processEvent = function (e)
  eventId = getEventType(e)
  if eventId == 3 then
    return 3
  else
    return 0
  end
end

describe("processEvent", function()
  it("calls getEventType with the event", function()
    stub(_G, "getEventType")
    processEvent(42)
    assert.stub(getEventType).was.called_with(42)
    getEventType:revert()
  end)
end)
```

**Comment by starius** [comment]
Thank you, @o-lim. I have two more problems.

1. Source of processEvent can not be changed.
2. Your code works, but when I replace `_G.getEventType = function(e)` with `function getEventType(e)`, it fails. I don't understand, why.

**Comment by o-lim** [comment]
busted tries to sandbox all test files, so any global variables that get created inside a file or `describe` block do not get added to `_G`.  Any new global variables are scoped to the current context block (e.g. the current file or `describe` block)

**Comment by o-lim** [comment]
If you can't change the source of processEvent, then would assume it is in it's own lua module and you would use it like so
```lua
-- processEvent.lua
function getEventType(e)
  ...
end

function processEvent(e)
  eventId = getEventType(e)
  if eventId == 3 then
    return 3
  else
    return 0
  end
end
```
```lua
-- process_event_spec.lua
require 'processEvent'

describe("processEvent", function()
  it("calls getEventType with the event", function()
    stub(_G, "getEventType")
    processEvent(42)
    assert.stub(getEventType).was.called_with(42)
    getEventType:revert()
  end)
end)
```
Since `processEvent` and `getEventType` are globals in the required file `processEvent.lua`, these functions will get added to `_G` when you do `require 'processEvent'`, so the test should work just fine.

**Comment by starius** [comment]
Thank you. The problem is solved.
:+1:
