### ISSUE TITLE
Get the name of the spec currently being executed

### ISSUE THREAD

**Issue by leafo** [Olivine-Labs/busted#406]
I have some specs that generate side effect files, I'd like to name them after the test I'm currently running. Is there a way to get the name of the current test I'm in?

Something like this would be preferable:

```lua
local busted = require "busted"
it("should get my name", function()
   assert.same("should get my name", busted.current_spec_name())
end)
```

It should get the full name including any nested describes.

**Comment by o-lim** [comment]
This sounds like something you could do in your own output handler.  Output handlers already have access to this information, and if you want your specs to output to a file, this sounds like a job for an output handler.  You could do something like
```lua
-- test_spec.lua
local busted = require 'busted'
it('this test wants to output to file', function()
  local output_data = { ... }
  busted.publish({'custom', 'output'}, output_data)
end)
```
```lua
-- output_handler.lua
return function(options)
  local busted = require 'busted'
  local handler = require 'busted.outputHandlers.utfTerminal'(options)
  local pretty = require 'pl.pretty'
  local currentTestName

  function handler.myTestStart(element, parent)
    currentTestName = handler.getFullName(element)
  end

  function handler.myTestEnd(element, parent, status, trace)
    currentTestName = nil
  end

  function handler.myCustomOutput(output_data)
    local filename = currentTestName .. '.txt'
    local f = io.open(filename, 'w')
    f:write(pretty.write(output_data))
    f:close()
  end

  busted.subscribe({'test', 'start'}, handler.myTestStart)
  busted.subscribe({'test', 'end'}, handler.myTestEnd)
  busted.subscribe({'custom', 'output'}, handler.myCustomOutput)

  return handler
end
```
```
$ busted -o output_handler.lua
```

**Comment by o-lim** [comment]
It sounds like you are trying to do two different things in your specs:
1. Verify program correctness
2. Generate output files

In my opinion, it would be cleaner to separate this into two separate responsibilities.  The specs should verify program correctness, while an output handler should be used to generate any output files that may be necessary.  This also makes it easier to modify the output file format without modifying the specs.

Is this something that makes sense for your specs or is there some other constraint that would make this type of thing difficult or infeasible?

**Comment by leafo** [comment]
I think the output handler should work well for my case, I haven't had a chance to try it out but I'll re-open the issue if it doesn't work.

Thanks
