### ISSUE TITLE
Fails to install 2.0.rc8-0

### ISSUE THREAD

**Issue by thibaultCha** [Olivine-Labs/busted#411]
Hi,

`luarocks install busted` is currently failing.

Mostly because of `2.0.rc8-0` and its mediator_lua dependency:

```lua
'mediator_lua >= 1.1.1-0',
```

Output error is:

```
Missing dependencies for busted:
mediator_lua >= 1.1.1-0
luassert >= 1.7.6-0

Using https://rocks.moonscript.org/mediator_lua-1.1.1-0.rockspec... switching to 'build' mode

Error: Failed installing dependency: https://rocks.moonscript.org/mediator_lua-1.1.1-0.rockspec - Error fetching file: Failed downloading https://github.com/Olivine-Labs/mediator_lua/archive/v1.1.1.tar.gz - HTTP/1.1 404 Not Found
```

It looks like mediator_lua does not have a `1.1.1` tag: https://github.com/Olivine-Labs/mediator_lua/releases

**Comment by number5** [comment]
same here.

The reason is https://github.com/Olivine-Labs/mediator_lua/commit/2131ef5b762e56a0910005f49a5790355fef6701

**Comment by amireh** [comment]
I believe https://github.com/Olivine-Labs/mediator_lua/pull/5 would fix this.

**Comment by o-lim** [comment]
Looks like there was a typo when a new version mediator was released.  A `1.1.0` release was made instead of `1.1.1`.  I think @ajacksified or @DorianGray just needs to remake the mediator release as `1.1.1`.  That should fix the install problems.

**Comment by number5** [comment]
As a workaround, we are now using https://rocks.moonscript.org/modules/kikito/busted-stable which is pointing to busted 1.11.1-1

**Comment by o-lim** [comment]
You could also use busted 1.11.1-2, which was just released today and does not use mediator and is compatible with the latest lua_cliargs.

**Comment by ajacksified** [comment]
Fixed mediator.
