### ISSUE TITLE
Busted + OpenResty

### ISSUE THREAD

**Issue by kirk7880** [Olivine-Labs/busted#414]
I am fairly new to lua and I am attempting to write some test cases. Busted is nice as it reminds me of mocha and it's an easy transition. The issue I am having is testing code for openresty. Looks like it's having trouble finding the resty.* modules (ie: require 'resty.md5').

Any suggestions on how to get around this or is it already known that busted doesn't work with openresty?

**Comment by kirk7880** [comment]
Example output:

```bash
0 successes / 0 failures / 1 error / 0 pending : 0.000421 seconds

Error → .//////lib/client.lua @ 9
test/test-inspect-useragent.lua
.//////lib/client.lua:9: module 'resty.md5' not found:No LuaRocks module found for resty.md5
	no field package.preload['resty.md5']
	no file './src/resty/md5.lua'
	no file './src/resty/md5/resty/md5.lua'
	no file './src/resty/md5/init.lua'
	no file '/Users/me/.luarocks/share/lua/5.1/resty/md5.lua'
	no file '/Users/me/.luarocks/share/lua/5.1/resty/md5/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/md5.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/md5/init.lua'
	no file './resty/md5.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-alpha/resty/md5.lua'
	no file '/usr/local/share/lua/5.1/resty/md5.lua'
	no file '/usr/local/share/lua/5.1/resty/md5/init.lua'
	no file './csrc/resty/md5.so'
	no file './csrc/resty/md5/resty/md5.so'
	no file '/Users/me/.luarocks/lib/lua/5.1/resty/md5.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/md5.so'
	no file './resty/md5.so'
	no file '/usr/local/lib/lua/5.1/resty/md5.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './csrc/resty.so'
	no file './csrc/resty/resty.so'
	no file '/Users/me/.luarocks/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

:bomb:

**Comment by DorianGray** [comment]
You just need to add the paths to the openresty libraries to your LUA_PATH variable

**Comment by kirk7880** [comment]
Excellent - I got it to work by doing just that. Thanks!

**Comment by Etiene** [comment]
Hello, I'm attempting the same thing, and I've done what was commented above, but I'm still getting some errors...

```
Error → /usr/local/openresty/lualib/resty/mysql.lua @ 6
suite tests/unit/openresty.lua
/usr/local/openresty/lualib/resty/mysql.lua:6: attempt to index global 'ngx' (a nil value)
```

Any ideas that could help me out here on how do I access the nginx var when running Busted? thanks :)

**Comment by DorianGray** [comment]
You would either need to run busted inside of nginx(I've never tried this before, it should work?) or you would need to mock the ngx variable.

**Comment by DorianGray** [comment]
Ah, here's the thing I was looking for. This is a good start, but is very incomplete for stubbing out the ngx variable. https://github.com/bsm/fakengx

**Comment by Etiene** [comment]
I started mocking the ngx variable but then I started having problems at ngx.socket :~

**Comment by DorianGray** [comment]
ngx.socket can be replaced with luasocket with some fairly minor changes in most cases. They implement the same socket interface...if you were to use the fakengx shim above and add a binding for luasocket for socket ops I bet it would serve you well.

**Comment by DorianGray** [comment]
You will get stuck with mysql_real_escape_string iirc, but that can be written by hand.

**Comment by DorianGray** [comment]
lol https://github.com/bsm/fakengx/pull/1 it looks like that project is pretty dead. If you fork it I'm sure I could contribute as well.

**Comment by Etiene** [comment]
aaaaaaaaaaaargh
I'm still really stuck with the socket thingie :~ I tried to mimic that too, but it's a hellhole... 
I'll breathe and get back to this later before I hit my computer, but your help has been really useful, thanks!

**Comment by Etiene** [comment]
I'll try the other way around again later, maybe it will be easier to require busted and run
resty start_tests.lua
But I was trying that earlier and hitting my head on a wall too ^^'

**Comment by nilnor** [comment]
@Etiene FWIW, we ended up with our own test runner run by `resty` at work. Started out with mocking things but that quickly became an issue as we used more of the openresty/nginx modules. So now we run `resty` instead, which loads our special test-loader file, which in turn sets up the environment and runs busted programmatically. Some hassle to setup, but it works very well now and let's us actually use everything we need from within the specs. We still need to fake certain things for the requests, etc. however, as they're depending on the nginx context. We're using the old, stable version of busted however, but I imagine there's not much different with the RCs.

**Comment by Etiene** [comment]
The problem is that I also tried to run Busted programatically and failed! The docs only suggest how to do it in one file using require 'busted.runner'(), but when I have multiple files with tests and a helper I just cant find my way around it. I'd like to be able to set the ROOT internally. I tried some ways and it didn't work. I'll try it again over here and update this in case I get it right. It must be something stupid I'm missing out :~ Could you give me some tips on how you proceeded?

**Comment by nilnor** [comment]
We didn't do anything particularly complicated, but perhaps it's due to us using stable and you using the the RCs then. Anyway, what we do is that we end up invoking `resty`, passing as the first parameter our custom initialization script followed by any other arguments. The initialization script invokes our init and sets up things and kicks off busted. The `busted.runner` is different from how things are in stable, so I'm afraid you're on your own there. Our custom init code for the stable version (which we vendor) is basically this:

```lua
-- [..]
_G.arg = arg
local busted = assert(loadfile(base_dir .. '/lib/spec-support/busted/busted_bootstrap'))
local moonscript = require "moonscript.base"
assert(moonscript.loadfile(base_dir .. '/spec/spec_helper.moon'))()
busted()
```

**Comment by DorianGray** [comment]
@nilnor @Etiene I finally went through and fixed this. I made a PR to resty-cli so you can now safely install it as your system lua interpreter. I have it working on my local machine by `vim $(which busted)` and swapping out luajit with resty, after installing it of course. It allows me to run busted inside nginx proper.

https://github.com/openresty/resty-cli

**Comment by ldeveloperl1985** [comment]
@DorianGray  How to run busted inside nginx? I am new in both nginx, lua and busted
Please give me steps.

**Comment by Tieske** [comment]
here's an example: https://github.com/Kong/kong/blob/master/bin/busted

it has some extra code to 'unset' enviornment variables to prevent them from impacting the tests.

Here's some patches used with that: https://github.com/Kong/kong/blob/master/kong/core/globalpatches.lua (note that only some of those patches apply to testing)

**Comment by ldeveloperl1985** [comment]
Thank you @Tieske . After applying patch files it works.

**Comment by kg0r0** [comment]
I also encountered the same problem.
I'm sorry, the link of patch is broken and I can't try it.

**Comment by Tieske** [comment]
@kg0r0 I updated the link to the new location

**Comment by kg0r0** [comment]
Thank you for the update!!

**Comment by Triple-Z** [comment]
> Here's some patches used with that: https://github.com/Kong/kong/blob/master/kong/globalpatches.lua (note that only some of those patches apply to testing)

I wonder how to handle the OpenResty APIs which cannot be used in `ngx.timer.*` context, such as `ngx.req.*` and `ngx.resp.*` etc.

I cannot find these functions mock/stub in that file.

**Comment by alerque** [comment]
@Triple-Z I think it's probably time to open a new issue to discuss that, the original context for this tracking issue isn't really relevant and hence most of the people subscribed don't need to be getting notifications on a closed resolved issue.

**Comment by Tieske** [comment]
just dropping this here for future reference:

To run unit tests with OpenResty, I recently created the following setup:
* file `./spec/resty-runner.lua` (make sure to make it executable):
    ```lua
    #!/usr/bin/env resty
    
    -- script to run Busted tests using Openresty while setting some extra flags.
    --
    -- This script should be specified as:
    --   busted --lua=<this-file>
    --
    -- Alternatively specify it in the `.busted` config file
    
    
    -- These flags are passed to `resty` by default, to allow for more connections
    -- and disable the Global variable write-guard. Override it by setting the
    -- environment variable `BUSTED_RESTY_FLAGS`.
    local RESTY_FLAGS=os.getenv("BUSTED_RESTY_FLAGS") or "-c 4096 -e 'setmetatable(_G, nil)'"
    
    -- rebuild the invoked commandline, while inserting extra resty-flags
    local cmd = {
      "exec",
      arg[-1],
      RESTY_FLAGS,
    }
    for i, param in ipairs(arg) do
      table.insert(cmd, "'" .. param .. "'")
    end
    
    local _, _, rc = os.execute(table.concat(cmd, " "))
    os.exit(rc)
    ```

* file `./.busted` configuration file

    ```lua
    return {
      default = {
        lua = "spec/resty-runner.lua",
        verbose = true,
        coverage = false,
        output = "gtest",
      },
    }
    ```

The above has the benefit of being self contained within your repository, and working out of the box. Busted can now be used as usual, simply by executing `busted`.

I probably should extract this as a separate Lua module.
