### ISSUE TITLE
Replace dkjson with lua-cjson

### ISSUE THREAD

**Issue by istr** [Olivine-Labs/busted#445]
It would be great if busted could switch the JSON parser from dkjson to lua-cjson.
lua-cjson
- [is more popular](https://luarocks.org/modules/luarocks/lua-cjson) than [dkjson](https://luarocks.org/modules/luarocks/dkjson) which is not an argument for itself, but this raises the probability you need to install / have installed lua-cjson anyway
- claims better compatibility (though I haven't checked lua-cjson against 5.3, but dkjson claims < 5.3 and lua-cjson >= 5.1)
- [is way faster](http://www.kyne.com.au/~mark/software/lua-json-performance.html)

Nearly any other module in my [OpenResty](http://openresty.org/)-based setup refers/uses lua-cjson when it comes to JSON with only [busted](https://github.com/Olivine-Labs/busted) introducing a second dependency on a different JSON parser.

**Comment by DorianGray** [comment]
lua-cjson had build problems on windows. That was the only reason we did not choose to use it. Have they been resolved?

**Comment by daurnimator** [comment]
> claims better compatibility (though I haven't checked lua-cjson against 5.3, but dkjson claims < 5.3 and lua-cjson >= 5.1)

dkjson works in 5.3 without issues.

In general, I prefer dkjson:
  - it's pure lua, which means you don't have to deal with compiling cjson (I run tests in places where I don't have a C compiler)
  - it has a sane options passing scheme

For a test suite, I prefer the correctness of dkjson over the speed of cjson.


However, if you're only using the basic `.decode` and `.encode` functions with a single argument, the apis are equivalent; and you can just swap out one for the other.

**Comment by istr** [comment]
Ok, point taken... https://github.com/Olivine-Labs/busted/issues/445#issuecomment-131679678
> (I run tests in places where I don't have a C compiler)

Maybe I can work out a solution based on [luarocks' dependency modes](https://github.com/keplerproject/luarocks/wiki/Dependencies) to drop "testing-only" dependencies from production builds -- the concept of "dev dependencies" is not available there.

**Comment by daurnimator** [comment]
> Maybe I can work out a solution based on luarocks' dependency modes to drop "testing-only" dependencies from production builds -- the concept of "dev dependencies" is not available there.

FWIW, I currently just install the testing only dependencies manually.
==> then for e.g. travis, I put them in there manually too. you usually install busted and luacov in this way already.

The manual-ness is a bit annoying, but it's really just 2 or 3 lines that you type once. Or a really minor step for a new developer joining the project.

**Comment by kamiccolo** [comment]
Using Lua 5.1.5 `dkjson` fails to generate proper output on most of Busted specs. 

Relevant issue:[#448](https://github.com/Olivine-Labs/busted/issues/448)
