### ISSUE TITLE
2.0.rc10-0 (Lua 5.1.5) does not produce JSON output on most of specs.

### ISSUE THREAD

**Issue by kamiccolo** [Olivine-Labs/busted#448]
Example:

    $ busted -v -o json ./cl_list.lua
    < returns nothing >
    $ echo $?
    1

    $ $ busted --shuffle -v -o json ./cl_randomize.lua
    < returns nothing >
    $ echo $?
    1

Though, following works properly:

    $ busted -v  ./cl_list.lua 
    3 successes / 0 failures / 0 errors / 0 pending : 0.000894 seconds
    $ echo $?
    0

    $ busted --shuffle -v ./cl_randomize.lua 
    100 successes / 0 failures / 0 errors / 0 pending : 0.019599 seconds
    $ echo $?
    0

    $ busted -v -o json ./cl_compile_fail.lua 
    {"successes":[],"errors":[{"message":"./cl_compile_fail.lua:3: '=' expected near 'here'","name":"./cl_compile_fail.lua","isError":true,"trace":[],"element":{"trace":[],"name":"./cl_compile_fail.lua","descriptor":"file"}}],"pendings":[],"duration":1.7000000000003e-05,"failures":[]}
    $ echo $?
    1

**Comment by o-lim** [comment]
Fixed with PR #449.  Looks like the json module doesn't like tables with functions in them.

**Comment by DorianGray** [comment]
will close as soon as we roll a new rc
