### ISSUE TITLE
Compatibility with Lua strict mode (etc/strict.lua)

### ISSUE THREAD

**Issue by sirnuke** [Olivine-Labs/busted#469]
[strict.lua](http://www.lua.org/extras/5.1/strict.lua) is a method of catching code that accesses unset globals.  Busted triggers an error when running test cases, which appears to be in the global environment setup.

A work around is to require strict.lua in before_each, though it's a little unwieldy.  Perhaps with some tweaking of Busted, it could be the more proper setup function.

For reference, I'm using LuaJIT, though I imagine the issue exists with Lua 5.1 & 5.2.

**Comment by SaintDako** [comment]
@sirnuke Did #477 fix this for you?

**Comment by sirnuke** [comment]
I just installed a newer version of busted, and strict mode appears fixed in busted 2.0.rc12-0
