### ISSUE TITLE
TAP output missing plan, and not showing failed tests.

### ISSUE THREAD

**Issue by benbarbour** [Olivine-Labs/busted#471]
When I run with the default output handler I get

    218 successes / 9 failures / 0 errors / 0 pending : 2.635552 seconds

followed by the 9 failure messages. However, wen I run with `-o TAP` I get (test names intentionally stripped):

```
ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9
ok 10
ok 11
ok 12
ok 13
ok 14
ok 15
ok 16
ok 17
ok 18
ok 19
ok 20
ok 21
ok 22
ok 23
ok 24
ok 25
ok 26
ok 27
ok 28
ok 29
ok 30
ok 31
ok 32
ok 33
ok 34
ok 35
ok 36
ok 37
ok 38
ok 39
ok 40
ok 41
ok 42
ok 43
ok 44
ok 45
ok 46
ok 47
ok 48
ok 49
ok 50
ok 51
ok 52
ok 53
ok 54
ok 55
ok 56
ok 57
ok 58
ok 59
ok 60
ok 61
ok 62
ok 63
ok 64
ok 65
ok 66
ok 67
ok 68
ok 69
ok 70
ok 71
ok 72
ok 73
ok 74
ok 75
ok 76
ok 77
ok 78
ok 79
ok 80
ok 81
ok 82
ok 83
ok 84
ok 85
ok 86
ok 87
ok 88
ok 89
ok 90
ok 91
ok 92
ok 93
ok 94
ok 95
ok 96
ok 97
ok 98
ok 99
ok 100
ok 101
ok 102
ok 103
ok 104
ok 105
ok 106
ok 107
ok 108
ok 109
ok 110
ok 111
ok 112
ok 113
ok 114
ok 115
ok 116
ok 117
ok 118
ok 119
ok 120
ok 121
ok 122
ok 123
ok 124
ok 125
ok 126
ok 127
ok 128
ok 129
ok 130
ok 131
ok 132
ok 133
ok 134
ok 135
ok 136
ok 137
ok 138
ok 139
ok 140
ok 141
ok 142
ok 143
ok 144
ok 145
ok 146
ok 147
ok 148
ok 149
ok 150
ok 151
ok 152
ok 153
ok 154
ok 155
ok 156
ok 157
ok 158
ok 159
ok 160
ok 161
ok 162
ok 163
ok 164
ok 165
ok 166
ok 167
ok 168
ok 169
ok 170
ok 171
ok 172
ok 194
ok 195
ok 196
ok 197
ok 198
ok 199
ok 200
ok 201
ok 202
ok 203
ok 204
ok 205
ok 206
ok 207
ok 208
ok 209
ok 210
ok 211
ok 212
ok 213
ok 214
ok 215
ok 216
ok 217
ok 218
ok 219
ok 220
ok 221
ok 222
ok 223
ok 224
ok 225
ok 226
ok 227
1..227
```

There's two things wrong with that, I think. First tests 173-193 are missing, which is every test in the file that has some failing tests. Second, shouldn't the test plan (the 1..227 line) be at the top of the output?

**Comment by benbarbour** [comment]
Incidently, those tests take waaay longer than the reported 2.6 seconds to run.

**Comment by o-lim** [comment]
Are you running the latest version of busted?  If the execution time is being significantly under reported, it's probably at least a few revs old.  I can't explain why you are not seeing results for 173-193.  I can't seem to reproduce the error you are getting.  Maybe it has something to do with the way your tests fail?  Can you see if you still get this behavior after you update to the latest version of busted?

The test plan does not need to be at the top of the output, it can be at the end. See https://testanything.org/tap-version-13-specification.html, under `TESTS LINES AND THE PLAN` and `Creative liberties`.

> The plan tells how many tests will be run, or how many tests have run. It's a check that the test file hasn't stopped prematurely. It must appear once, whether at the beginning or end of the output. The plan is usually the first line of TAP output (although in future there may be a version line before it) and it specifies how many test points are to follow.

The way tests are discovered in busted prevents the TAP output handler from outputting the plan at the beginning, unless you want to wait until all tests have completed before seeing any output. Basically, the number of tests is not known until all tests have been run.

**Comment by benbarbour** [comment]
It was an older version, the times seem better now. I never did figure out why the tests were missing. We just switched to another output format.

Thanks for the info about the tap specification!
