### ISSUE TITLE
How do I use this without luarocks?

### ISSUE THREAD

**Issue by farzher** [Olivine-Labs/busted#479]
`require('busted.runner')()` doesn't work because  `module 'pl.path' not found`

**Comment by DorianGray** [comment]
You will have to manually install all of the dependencies and make them available on your LUA_PATH... I would suggest using luarocks if at all possible, it makes things much easier.

**Comment by DorianGray** [comment]
The dependencies and associated versions are listed in the .rockspec files. I would suggest looking at the "scm" one.

**Comment by farzher** [comment]
I see, thanks,

I can't figure out how to install luarocks... I'm on windows, and it's a mess
![](http://i.imgur.com/V8XXqAR.png)
![](http://i.imgur.com/LSukkwN.png)

(You don't have to help with this, I'm just explaining why I don't use luarocks)

**Comment by DorianGray** [comment]
You just need to install lua and make lua.exe available on your $PATH variable.

**Comment by DorianGray** [comment]
...or alternatively make that /LUA switch point to the correct executable, not just the folder.

**Comment by farzher** [comment]
I wish it was that simple. I have lua working

![](http://i.imgur.com/QSN1X7K.png)

**Comment by farzher** [comment]
I pointed to the .exe, but as you can see luarocks is apparently looking for `lua.h`, which I don't have anywhere, I just have lua biniaries

**Comment by DorianGray** [comment]
You should have lua.h in your lua install...where did you get the lua binaries?

**Comment by farzher** [comment]
haha, oh. interesting!

I think I installed lua from this section of lua.org
![](http://i.imgur.com/wCelMLX.png)


I just got a fresh lua using this site https://code.google.com/p/luaforwindows/ and now luarocks is working. Thanks!

**Comment by DorianGray** [comment]
No problem! Glad to help =) ...although I didn't do much.

**Comment by farzher** [comment]
although actually installing busted isn't working /:

![](http://i.imgur.com/zBLDNuk.png)

**Comment by DorianGray** [comment]
Try getting latest master and running luarocks make busted-scm-0.rockspec

**Comment by Tieske** [comment]
Regarding installing LuaRocks on Windows; might be easiest if you temporarily add the lua executable to your systempath. The installer will by default search the system path.

alternatively check here; http://www.thijsschreijer.nl/blog/?p=863 

and more recently we've been developing [luawinmake](https://github.com/Tieske/luawinmake) and [luawinmulti](https://github.com/Tieske/luawinmulti) but I've not yet written an updated blog post on those.
