### ISSUE TITLE
Is it possible to run Eclipse debugger without require 'busted.runner'() incantation?

### ISSUE THREAD

**Issue by romanchyla** [Olivine-Labs/busted#492]
This is about the Eclipse Lua debugger. Normally, the Eclpse LDT will start lua scripts with -e 'require debugger'() - which opens a remote socket and listens for connections. I spent some time making it work with busted

1) I tried setting 'busted' as my interpreter for Eclipse in the hope that I can debug inside Eclipse, yet it fails with the error ``busted: error: unknown/bad flag: -e; re-run with --help for usage.```

2) then I tried using normal lua interpreter, adding -e "require 'busted.runner'()" as an argument to the lua, but fails as well

```
======= Provided command line =============
/usr/bin/lua: /usr/local/share/lua/5.1/cliargs.lua:488: attempt to get length of global 'arg' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/cliargs.lua:488: in function 'parse'
	/usr/local/share/lua/5.1/busted/modules/cli.lua:155: in function </usr/local/share/lua/5.1/busted/modules/cli.lua:153>
	(tail call): ?
	/usr/local/share/lua/5.1/busted/runner.lua:34: in function </usr/local/share/lua/5.1/busted/runner.lua:9>
	(command line):1: in main chunk
	[C]: ?
```

3) the only option that works, is to copy LUA_PATH and LUA_CPATH from inside the busted script, set them as env vars in eclipse and do  require 'busted.runner'() at the beginning of each debugged file [which is not great]

Is there a way around it?

Please see #490 and #491 for descriptions of other problems/solutions I found

**Comment by o-lim** [comment]
There isn't really a way to run the debugger without `require 'busted.runner'()`.  This feature was actually added to enable debugging.  However, you should not need to set LUA_PATH or LUA_CPATH in Eclipse.  If you installed everything with luarocks, the default LUA_PATH and LUA_CPATH should work, unless Eclipse changes the system default values to something else.

**Comment by romanchyla** [comment]
So I managed to run the debugger (inside Eclipse) using a modified 'busted' script. (the unmodified busted complains about 'unknown -e' argument)

the original:

```
exec "/usr/bin/lua" -lluarocks.loader "/usr/local/lib/luarocks/rocks/busted/2.0.rc10-0/bin/busted" "$@"
```

the modified version:

```
args=( "$@" )
newargs=()
opts=()
for (( i = 0 ; i < ${#args[@]} ; i=$i+1 )); do
  if [ "${args[${i}]}" == "-e" ]; then
    opts+="${args[${i}]}"
    i=$i+1
    opts+="${args[${i}]}"
  else
    newargs+="${args[${i}]}" 
  fi
done
exec "/usr/bin/lua" "$opts" -lluarocks.loader "/usr/local/lib/luarocks/rocks/busted/2.0.rc10-0/bin/busted" "$newargs"
```

it sure is a hack, but a very useful one! :) maybe you have an idea how to make it more generic, but I'm happy

**Comment by o-lim** [comment]
I updated PR #493 with a -e option for `busted`.  Maybe you can give this a try?  If it works, then you won't have to modify the `busted` script.

**Comment by romanchyla** [comment]
I'll give it a try later today and get back to you

**Comment by DorianGray** [comment]
It's in master  now.
