### ISSUE TITLE
Checking for lua's default assert?

### ISSUE THREAD

**Issue by rm-code** [Olivine-Labs/busted#495]
In one of my modules I have asserts like this:
```lua
assert( target:instanceOf( 'Door' ), 'Target tile needs to be an instance of Door!' );
assert( not target:isPassable(), 'Target tile needs to be impassable!' );
assert( target:isAdjacent( character:getTile() ), 'Character has to be adjacent to the target tile!' );
```

Is there a way to check if these fail via busted? Or do I have to replace all of them with:

```lua
if not foo then
    error( 'bar' )
end
```
??

**Comment by DorianGray** [comment]
We don't override the default assert behavior and busted does catch those cases. This should work already, did you test it?

**Comment by rm-code** [comment]
> We don't override the default assert behavior and busted does catch those cases. This should work already, did you test it?

Just got home and noticed I didn't use an anonymous function to wrap my code in ... It's working now. Sorry for the noise!
