### ISSUE TITLE
When was_called_with fails output should show args expected and passed

### ISSUE THREAD

**Issue by jodonnell** [Olivine-Labs/busted#497]
This would make debugging much faster.

**Comment by jodonnell** [comment]
(unrelated but dns fails when i try to visit olivinelabs.com)

**Comment by o-lim** [comment]
This can easily result in output that overwhelms the user.  For example, consider the following:
```lua
it('fails was_called_with', function()
  local foo = function() end
  spy(foo)
  for i = 1,1000 do
    foo(i)
  end
  assert.spy(foo).was_called_with(0) -- should this failure show all 1000 args to foo?
end)
```
If you only ever call `foo` one time, then it's not really a problem, but if you call it more than once, or many many times, then you would have to show all args for all calls to `foo`.

Btw, this is part of `luassert`, not `busted`, and should probably be an issue for `luassert`.
