### ISSUE TITLE
Busted scm-0 on LuaRocks

### ISSUE THREAD

**Issue by xspager** [Olivine-Labs/busted#498]
Hi,

I'm trying to install the scm-0 version of Busted with LuaRocks because I want to be able to use lua_cliargs 3.0-1, can this version be made available? There is this version https://luarocks.org/modules/olivine-labs/busted/scm-0 there but it is not using the latest lua_cliargs version and I can't install it anyway.

I can install Busted scm-0 with the rockspeck URL (https://raw.githubusercontent.com/Olivine-Labs/busted/master/busted-scm-0.rockspec) but I would rather not to do that.

**Comment by ajacksified** [comment]
Released `v2.0.rc12-1`, which has cliargs 3.0-1. Also updated scm-0.
