### ISSUE TITLE
Release new version that works with lua-cliargs >=3.0

### ISSUE THREAD

**Issue by n0la** [Olivine-Labs/busted#501]
Hi,

I am the guy that tries to port busted to [OpenBSD](https://github.com/n0la/luaports). The sad thing is that the current release of busted (v2.0.rc11-0) does not yet have the fixes in place to support lua-cliargs >= 3.0. Could you please a new version with those fixes in place? It would spare some manual [patching](https://github.com/n0la/luaports/blob/master/devel/lua-busted/patches/patch-busted_modules_cli_lua) in the port.

Thanks.

**Comment by n0la** [comment]
It is also requested here #498.

**Comment by o-lim** [comment]
Any chances for an rc12 release?

**Comment by ajacksified** [comment]
Released `v2.0.rc12-1`.
