### ISSUE TITLE
pattern CLI argument seems not to work (or poorly documented)

### ISSUE THREAD

**Issue by dannybloe** [Olivine-Labs/busted#504]
Hi folks, 

Happy to have found busted!

I'm trying to use the --pattern cli switch no matter what I try it fails to run any test. 

I'm using WebStorm and I configured a bash command that should start busted in the context of my test folder but it fails to see any files. All my test files start with the name `test` so I thought I could do something like this:

`busted test*` or `busted -p test*`

But nothing seems to run any test other than specifying the exact filename.

**Comment by Tieske** [comment]
have you tried `busted test` ?

The pattern is a Lua pattern iirc (string matching)

**Comment by dannybloe** [comment]
Yes I tried that and also this `busted -p *` From the command line that works. But in Webstorm (Intellij) I can configure a Run/Debug configuration:

<img width="569" alt="screen shot 2016-03-18 at 17 25 04" src="https://cloud.githubusercontent.com/assets/2369994/13884472/7495aea8-ed2e-11e5-9e4e-0da60a772918.png">

Strangely, in that case the -p option doesn't seem to work.

**Comment by DorianGray** [comment]
Try -p '*'

**Comment by Tieske** [comment]
the cliargs module used by Busted to parse the command line contains a special option to dump what it received. Use `--__DUMP__` as the very first option (2 dashes, and 2x2, so 4 in total, underscores). That way you can see what Busted actually receives, and then do some trial and error with escaping the arguments. 

see https://github.com/amireh/lua_cliargs#changes-in-200-from-1xx

**Comment by dannybloe** [comment]
Well, I think I have found it. This has to be the command line args:

`--pattern=.* .`

Obviously it wasn't telling me that I ommitted the ROOT (.) and that the pattern had to be a regexp (that's my assumption). The `.` in `.*` was essential. Perhaps someone can add that information to the docs :)

Thanks for the help anyway :-)

**Comment by dannybloe** [comment]
Interestingly: this works too:
`--pattern=test* .` (without the `.` before the `*`). Weird.

**Comment by mpeterv** [comment]
`busted --help` shows this for `-p, --pattern=PATTERN`: `only run test files matching the Lua pattern (default: _spec)`. You can read about Lua patterns here in [the manual](http://www.lua.org/manual/5.3/manual.html#6.4.1). In particular, `.*` matches all strings, `*` matches literal asterisk, `test*` matches strings containing `tes`.
