### ISSUE TITLE
Support for .only

### ISSUE THREAD

**Issue by dannybloe** [Olivine-Labs/busted#505]
Hi folks, 

I'd like to request for a new feature. In many javascript testing frameworks you can add `.only` to `it` and `describe` after which the testrunner only runs these specific tests:

```
describe(..., function()
    it.only('should', function () end)
end)
```

or

```
describe.only(..., function()
    it('should', function () end)
end)
```

This is very handy if you quickly want to run only that particular test without having to add tags, change command line arguments etc etc. 

See: [https://mochajs.org/#exclusive-tests]

**Comment by Tieske** [comment]
You can already do this using tags.

```lua
describe("A describe block", function()
    it('should #only', function () end)
end)
```

and then call the commandline using the tag argument

**Comment by dannybloe** [comment]
Not even close to the convenience of mocha's way. Like I said using #tag you have to change two things instead of one.

**Comment by DorianGray** [comment]
Just don't forget to remove the .only's.

I think this is a good feature to have, but I think that tags are a much more powerful way of doing this. Also, safer, since if you accidentally leave a #only tag in a commit you won't break your CI.

**Comment by Tieske** [comment]
@dannybloe sorry, I missed your remark on the tags in the original post.

Then again, I prefer tags, and I hate a dozen ways to do the same thing, only adds bloat. My 2cts.

**Comment by o-lim** [comment]
You can also use the `--filter` option, which will filter tests by name, then you only have to change one thing (the command line), as long as your test name is unique.
