### ISSUE TITLE
Penlight 1.4.0 breaks build

### ISSUE THREAD

**Issue by smhxx** [Olivine-Labs/busted#528]
Hi there!

Just thought I'd leave you a heads-up as a warning that Busted's next CI build is going to fail. I actually just ran into this problem myself on my own project, caused by a new version of Penlight that was pushed to Luarocks about 3 hours ago. Luarocks will use the new version (1.4.0-1) by default since it falls within the `>=1.3.2-2` rule in Busted's rockspec files, and something's changed in ~~`pl.path`~~ `pl.dir` that's causing problems. ~~I'm not actually sure the direct cause of the problem,~~ _(_**_EDIT:**_ _It's a bug in Penlight. See below.)_ but when I run `busted spec` with the latest version of Penlight, Busted is no longer able to find the test files.

```
smhxx@Development:~/GitHub/busted$ sudo luarocks make busted-2.0.rc12-1.rockspec 
Updating manifest for /usr/local/lib/luarocks/rocks
busted 2.0.rc12-1 is now built and installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

smhxx@Development:~/GitHub/busted$ busted spec

0 successes / 0 failures / 1 error / 0 pending : 0.000033 seconds

Error → No test files found matching Lua pattern: _spec

smhxx@Development:~/GitHub/busted$ sudo luarocks make busted-scm-0.rockspec 
Updating manifest for /usr/local/lib/luarocks/rocks
busted scm-0 is now built and installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

Checking stability of dependencies on the absence of
busted 2.0.rc12-1...

Removing busted 2.0.rc12-1...
Removal successful.
smhxx@Development:~/GitHub/busted$ busted spec

0 successes / 0 failures / 1 error / 0 pending : 0.000022 seconds

Error → No test files found matching Lua pattern: _spec
```

Anyway, I'm just updating my .travis.yml for now to use the older version of Penlight, just thought I'd help out and bring this to your attention so that it doesn't come as a surprise the next time you commit. Cheers!

**Comment by smhxx** [comment]
To clarify, I've done some digging and determined that this is a bug in Penlight's `dir.getallfiles()` method. I'm pretty sure Busted should be fine once it is resolved. I'm working on a PR now and will submit it to Penlight tonight.

**Comment by jszakmeister** [comment]
FWIW, this issue manifests itself as the following when running with TAP support:

```text
/Users/jszakmeister/projects/neovim/neovim/.deps/usr/bin/luajit: ...im/.deps/usr/share/lua/5.1/busted/outputHandlers/TAP.lua:33: attempt to concatenate field 'currentline' (a nil value)
stack traceback:
       	...im/.deps/usr/share/lua/5.1/busted/outputHandlers/TAP.lua:33: in function 'showFailure'
       	...im/.deps/usr/share/lua/5.1/busted/outputHandlers/TAP.lua:72: in function 'fn'
       	...jects/neovim/neovim/.deps/usr/share/lua/5.1/mediator.lua:103: in function 'publish'
       	...ps/usr/share/lua/5.1/busted/modules/test_file_loader.lua:93: in function 'testFileLoader'
       	.../neovim/neovim/.deps/usr/share/lua/5.1/busted/runner.lua:158: in function <.../neovim/neovim/.deps/usr/share/lua/5.1/busted/runner.lua:11>
       	...deps/usr/lib/luarocks/rocks/busted/2.0.rc12-1/bin/busted:3: in main chunk
       	[C]: at 0x01000010c0

CMake Error at /Users/jszakmeister/projects/neovim/neovim/cmake/RunTests.cmake:39 (message):
  Running unit tests failed with error: 1.
```

**Comment by smhxx** [comment]
**Update:** The bugfix is now [merged into Penlight/master](https://github.com/stevedonovan/Penlight/commit/f949b64341a0e003b5fe987402c4fd7f84becf52), so the next time they push to Luarocks it should fix everything. I guess it's up to the maintainer whether they're going to do a 1.4.0-2 version right away (I would hope so) or wait to see if any new problems crop up. All in all, it's been a year since the last update to Penlight, so *something* was pretty much guaranteed to be off... good thing it was literally a one-character fix! (Smallest PR ever?)

**Comment by ajacksified** [comment]
I'll point to 1.4.0-2 (or whatever they choose) once it goes live - thanks!

**Comment by mpeterv** [comment]
Penlight 1.4.1 has been released with a fix for this issue.

**Comment by smhxx** [comment]
Cool, thanks @mpeterv!
