### ISSUE TITLE
Is busted supported on windows?

### ISSUE THREAD

**Issue by xinghuipan** [Olivine-Labs/busted#530]

**Comment by ajacksified** [comment]
yeah

**Comment by xinghuipan** [comment]
how to run the busted ? luarocks has been installed，I'm new to busted , please tell me datails?thanks @ajacksified

**Comment by DorianGray** [comment]
`luarocks install busted`

`busted`

Since you're on windows, you may also need to add the path to the place busted is installed to your PATH environment variable.

**Comment by xinghuipan** [comment]
luarocks  supported lua 5.3？
