### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by sigmasoldi3r** [Olivine-Labs/busted#538]
I have a problem installing the dependency of [luasystem](https://luarocks.org/modules/olim/luasystem) with Luarocks.

The main problem is `time.obj : error LNK2019: unresolved external symbol _luaL_setfuncs referenced in function _time_open` and this is if I use VisualStudio Developer Comand prompt for VS2015, else I will get a `"cl" is not a recognized internal or external bla bla...` at some point when trying to satisfy _busted's_ dependencies.

Ofcourse if I try to `luarocks install busted` I _cannot_ install it. I would like to use busted but... I cannot install it. Any ideas?

__Thanks!__

Full CMD output
> luarocks install luasystem
Installing https://luarocks.org/luasystem-0.2.1-0.src.rock...
Using https://luarocks.org/luasystem-0.2.1-0.src.rock... switching to 'build' mode
cl /nologo /MD /O2 -c -Fosrc/core.obj -IC:/Users/pblancoceldran/Documents/lua5_3_3/include/ src/core.c -DWINVER=0x0600 -D_WIN32_WINNT=0x0600
core.c
cl /nologo /MD /O2 -c -Fosrc/compat.obj -IC:/Users/pblancoceldran/Documents/lua5_3_3/include/ src/compat.c -DWINVER=0x0600 -D_WIN32_WINNT=0x0600
compat.c
cl /nologo /MD /O2 -c -Fosrc/time.obj -IC:/Users/pblancoceldran/Documents/lua5_3_3/include/ src/time.c -DWINVER=0x0600 -D_WIN32_WINNT=0x0600
time.c
link -dll -def:core.def -out:system/core.dll C:/Users/pblancoceldran/Documents/lua5_3_3/lua5.1.lib src/core.obj src/compat.obj src/time.obj
Microsoft (R) Incremental Linker Version 14.00.24213.1
Copyright (C) Microsoft Corporation.  All rights reserved.

>   Creating library system/core.lib and object system/core.exp
time.obj : error LNK2019: unresolved external symbol _luaL_setfuncs referenced in function _time_open
system/core.dll : fatal error LNK1120: 1 unresolved externals

> Error: Build error: Failed compiling module system/core.dll

**Comment by Tieske** [comment]
this is not a busted issue but of the dependency; luasystem by @o-lim

**Comment by o-lim** [comment]
Looks like you are using Lua 5.3.3 headers, but then trying to link with lua5.1.lib, instead of lua5.3.lib. The Lua include directory must match the Lua library version you are trying to link against.  You probably have a bad configuration for lurarocks, or you have a messed up installation of Lua.

**Comment by sigmasoldi3r** [comment]
Sorry! I'll check!
