### ISSUE TITLE
Busted Only works for lua 5.1

### ISSUE THREAD

**Issue by samdup123** [Olivine-Labs/busted#542]
Hey so busted wasn't running some functions for me (like goto and table.move etc) I went into the busted file and it looks like this

     #!/bin/sh

     exec '/usr/bin/lua5.1' -e 'package.path="/home/sam/.luarocks/share/lua/5.1/?.lua;/home/sam/.luarocks/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;"..package.path; package.cpath="/home/sam/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;"..package.cpath' -e 'local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("busted","2.0.rc12-1")' '/usr/local/lib/luarocks/rocks/busted/2.0.rc12-1/bin/busted' "$@"

Is there a way to make this run my lua 5.3 file  /usr/local/bin/lua ?

**Comment by mpeterv** [comment]
It looks like you have installed busted using Luarocks configured for Lua 5.1.

**Comment by DorianGray** [comment]
Yeah, that file is generated by luarocks. You need to reinstall luarocks for a different lua version to get this to work.
