### ISSUE TITLE
can't get async() to work.

### ISSUE THREAD

**Issue by fennecdjay** [Olivine-Labs/busted#545]
I tried various installation patterns, but everytime I hit
```
attempt to call a nil value (global 'async')
```
Any Hints?

**Comment by ajacksified** [comment]
You'll want to use version 1x, rather than version 2x, for async support.

**Comment by fennecdjay** [comment]
Ok. thanks.

**Comment by jojo59516** [comment]
> You'll want to use version 1x, rather than version 2x, for async support.

Is there any plan to bring `async` back to version 2x?
