### ISSUE TITLE
Error in output handler base.lua

### ISSUE THREAD

**Issue by forflo** [Olivine-Labs/busted#546]
Hi,

I have a strange error regarding the base output handler. I'm using the version 2.0.rc12-1 

I ran busted as follows

```
busted -lpath "./source/?.lua" tests/test_bashEdsl.lua
```
which leads to the following output:
```
/usr/share/lua/5.3/busted/outputHandlers/base.lua:146: bad argument #1 to 'insert' (table expected, got nil)
```

The test code is probably not the cause of this problem. However, here is it:
```lua
describe("general bash EDSL tests #BDSL", function()
             randomize(true)

             b = require "../source/bashEdsl"

             it("tests whether package was loaded correctly", function()
                    assert.Truthy(b)
             end)

             it("tests verbatim parameters #VP", function()
                    assert.True(b.c("foo")() == "foo")
             end)

             it("tests a simple parameter expansion use cases #PE", function()
                    assert.are.equal(b.pE("foo")(), [[${foo}]])
             end)

             it("tests parameter expansion use cases #PE", function()
                    assert.True(true)

                    assert.True((b.pE("foo") .. b.pE(b.pE("bar")))() ==
                        [[eval eval ${foo}\${${bar}}]] ) end)
end)
```

## Brainstorming

In base.lua:146 there is a little if - elseif cascade that compares the status variable against different strings. `status` seems to be a table here. Am I missing something crucial?

**Comment by forflo** [comment]
Uhm, as it turned out, I forgot that I've overwritten the function tostring in the global environment.

As soon as I commented out my custom tostring, everything worked as to be expected.

However, the documentation should mention that you cannot do such a thing in conjunction with your library...

**Comment by ajacksified** [comment]
"Don't override global functions" isn't something I think needs to be documented, but glad you got it working!
