### ISSUE TITLE
Typo in the website

### ISSUE THREAD

**Issue by AlexandreRio** [Olivine-Labs/busted#547]
I don't know if this is the right place to report a typo on the website since it's not generated from source from here. Anyway:
To register a new output handler, the [doc](http://olivinelabs.com/busted/#output-handlers) says to use the following line:
```lua
local handler = require("busted.outputHandler.base")()
```
Which should actually be:
```lua
local handler = require("busted.outputHandlers.base")()
```

**Comment by Tieske** [comment]
@ajacksified tried to find the docs repo, but couldn't find it? where is the site source?

**Comment by ajacksified** [comment]
@Tieske [gh-pages branch](https://github.com/Olivine-Labs/busted/tree/gh-pages) on this repo

**Comment by Tieske** [comment]
duh...

**Comment by Tieske** [comment]
thx @AlexandreRio
