### ISSUE TITLE
"Segmentation fault: 11"

### ISSUE THREAD

**Issue by randomeizer** [Olivine-Labs/busted#548]
Hi there. I'm trying to run `busted` on Mac OS X 10.11.6, and when doing anything with it, I get a "Segmentation fault: 11" error. I've looked around but can't find any specific remedies. Is this a problem with my lua configuration? I'm using lua 5.3.3.

Thanks!

**Comment by mpeterv** [comment]
Is there any other output other than segmentation fault? What are the versions of busted and its dependencies (run `luarocks show busted`)? Can you require the C dependencies (run `lua -l term`, `lua -l lfs`, `lua -l system`)?

**Comment by Tieske** [comment]
@randomeizer what Lua version? are you using LuaJIT by chance? there are issues if you try to use the ffi, as it might get GC'ed and cause a segfault.

**Comment by randomeizer** [comment]
Hey there, sorry for the delay in response. Here are some details:

1. No, no other output other than that short phrase.
2. busted 2.0.rc12-1 (I literally installed it for the first time earlier in the day)
3. I'm not sure exactly what display you're expecting from the three `lua` commands, but they all output this:
`Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio`
and then have a command prompt.
4. I installed LuaJIT after this was causing issues hoping it might help, but it made no change. I haven't configured it at all. For the record, the version is `LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/`

Any ideas?

**Comment by Tieske** [comment]
@randomeizer Only now seeing you use Lua 5.3.3 (in your op), so sorry for the noise on LuaJIT. To be safe, better remove LuaJIT again.

Lua itself is a 'safe' language, hence it shouldn't crash with a segfault. So maybe clean the environment and reinstall Lua and any libraries you use, as there probably is an issue somewhere on the c-side of things.

**Comment by liwangqian** [comment]
@randomeizer If you use luacov, makesure `runreport` to be `false` while `deletestats = true`

**Comment by Tieske** [comment]
closing this, likely a C-type thing
