### ISSUE TITLE
Helper script failures don't make busted fail

### ISSUE THREAD

**Issue by daurnimator** [Olivine-Labs/busted#549]
I wrote a helper script that throws an error if the environment is not suitable.
Busted logs the error, however it doesn't prevent it from running tests, nor does it exit with a non-zero code.

> busted: error: Cannot load helper script: spec/helper.lua
> spec/helper.lua:28: Locale not available

**Comment by daurnimator** [comment]
I worked around this with `os.exit(1)` for now... https://github.com/daurnimator/lua-http/commit/4f4d7194f128dff903d44c18e39da769e54a4308

**Comment by Tieske** [comment]
ran into this myself today, fix in #638
