### ISSUE TITLE
[2.0.rc12-0] pending not counted in summary

### ISSUE THREAD

**Issue by H8UL** [Olivine-Labs/busted#551]
I've created a simple test; I get successes as expected, but no matter what I try I don't get pending tests to count; the summary always shows 0 pending.

Here's my simple test:

```lua
describe("Complimentary-Multiply-With-Carry RNG", function()
    describe("RNG interface", function()
        it("should accept seed 0", function()
        end)
        it("should accept seed 1", function()
        end)
        pending("error when seed is nil")
        pending("various rand methods")
        pending("derived RNGs don't affect original RNG")
    end)
    describe("statistical tests of RNG", function()
        pending("implement some of the class RNG tests")
    end)
end)
```

I've only just installed busted, so I am not customizing any settings. I tried various things: running test from folder, running explicitly named test file, explicitly setting command line options both to --suppress-pending and --no-suppress-pending. I've also tried commenting out the successful tests, putting assertions in... Nothing seems to get that pending count above 0.

**Comment by mpeterv** [comment]
When used outside `it` blocks, `pending` needs a function body:

```lua
pending("description", function()
   -- test body
end)
```

The idea is that you can just replace `it` with `pending` to mark a test as pending.

There is no error and no effect whatsoever when using pending with a single argument like in your test because there is alternative syntax for `pending` and other blocks that uses chain calls:

```lua
describe "test" (function()
   it "something" (function()

   end)

   pending "something else" (function()

   end)
end)
```

So when you use `pending` with a single string argument `busted` expects you to call returned value again with a function, and the first call does not do anything on its on.

The situation is different for `pending` calls inside `it` blocks, there a single string argument works:

```lua
it("test", function()
   pending("this test is pending...")
end)
```

**Comment by H8UL** [comment]
Oh I see, that's quite powerful. So in the following updated example:

```lua
describe("Complimentary-Multiply-With-Carry RNG", function()
    describe("client interface", function()
        it("should accept seed 0", function()
            local rng = Cmwc:withSeed(0)
            rng:randUint32()
        end)
        it("should accept seed 1", function()
            local rng = Cmwc:withSeed(1)
            rng:randUint32()
        end)
        pending("error when seed is nil", function()
        end)
        pending("various rand methods", function()
        end)
        pending("derived RNGs don't affect original RNG", function()
            assert.are.same("no", "chance")
        end)
    end)
    describe("statistical tests of RNG", function()
        pending("implement some of the class RNG tests", function()
            error("whoops")
        end)
    end)
end)
```

The assert and error are skipped -- so pending acts as a error("whoops") doesn't get run. That means I can implement as much of the pending tests as I like without them failing, or switch an existing test to pending to ignore it? Did I get the intention right? That's very cool.

**Comment by mpeterv** [comment]
Yes, exactly :smile:

**Comment by H8UL** [comment]
That's really impressive, I just updated my example too to show off the pending at a higher "describe" level, too.

Feel free to close 😄
