### ISSUE TITLE
Calling busted with no arguments fails to find spec file

### ISSUE THREAD

**Issue by ryanford-frontend** [Olivine-Labs/busted#552]
Seemingly similar symptoms as the [penlight issue](https://github.com/Olivine-Labs/busted/issues/528), calling busted with no arguments returns:

```
user:~/exercism/lua/hello-world$ busted

0 successes / 0 failures / 1 error / 0 pending : 0.000048 seconds

Error → No test files found matching Lua pattern: _spec
```

but calling busted with "." as the argument works as intended.

```
user:~/exercism/lua/hello-world$ busted .
●
1 success / 0 failures / 0 errors / 0 pending : 0.002464 seconds
```

I'm using 

busted
   2.0.rc12-1 (installed) - /home/user/.luarocks/lib/luarocks/rocks
   2.0.rc12-1 (installed) - /home/user/.luarocks/lib/luarocks/rocks

penlight
   1.5.2-1 (installed) - /home/user/.luarocks/lib/luarocks/rocks
   1.5.2-1 (installed) - /home/user/.luarocks/lib/luarocks/rocks

**Comment by Tieske** [comment]
seems you have your `_spec` files at the top level. The default is to put the spec files in `./spec`. So if you move the files there, then you won't have to specify a location.
