### ISSUE TITLE
busted doesn't run tests for luarocks-site

### ISSUE THREAD

**Issue by aajjbb** [Olivine-Labs/busted#553]
Hi, I've been trying to run the tests of the [LuaRocks-site](https://github.com/luarocks/luarocks-site) project for a while but without success.

The error message from busted:

`/home/aajjbb/.luaver/lua/5.1/bin/lua: ...r/luarocks/2.4.0_5.1/share/lua/5.1/busted/runner.lua:14: bad argument #-1 to 'isatty' (FILE* expected, got table)                                       
stack traceback:
        [C]: in function 'isatty'
        ...r/luarocks/2.4.0_5.1/share/lua/5.1/busted/runner.lua:14: in function 
<...r/luarocks/2.4.0_5.1/share/lua/5.1/busted/runner.lua:11>
        .../lib/luarocks/rocks-5.1/busted/2.0.rc12-1/bin/busted:3: in main chunk
        [C]: ?
`

`lua 5.1`
`busted 2.0.rc12-1`

All installed through `luaver`

**Comment by Tieske** [comment]
I think you should ask for help at the `luarocks-site` project, as it depends on how they use `Busted` in their test infrastructure.

**Comment by aajjbb** [comment]
Okay then, as it's my first time using busted I thought the error could be in the busted version. 

Thanks

**Comment by mpeterv** [comment]
This is a combination of issues in lua-term, and Lua 5.1, the first patch version of 5.1.x. Install Lua 5.1.5 or build lua-term from master to avoid it. See hoelzro/lua-term#18.

**Comment by aajjbb** [comment]
Thanks a lot @mpeterv I'm not in my notebook now so I'll test it tonight.

**Comment by aajjbb** [comment]
Just tested and updating for Lua 5.1.5 solved the issue. Once again, thanks @mpeterv
