### ISSUE TITLE
Execution/elapsed time of each test

### ISSUE THREAD

**Issue by henriquechehad** [Olivine-Labs/busted#557]
I saw there is a total time elapsed when busted finishes the execution of tests. 

Could be good another option to show the elapsed time of each test.

Is there already an option for it? Or need be implemented?

**Comment by Tieske** [comment]
the core generates the data, but it is up to the output handler whether it is actually displayed. Iirc the `gtest` output handler does show per test times.

Run `busted -o gtest` for example
