### ISSUE TITLE
Private section in the documentation not accurate

### ISSUE THREAD

**Issue by bonidjukic** [Olivine-Labs/busted#560]
I ran into issues while trying to test private functions as per the [documentation](https://olivinelabs.com/busted/#private):

```
local mymodule = require("mymodule")

describe("Going to test a private element", function()

  setup(function()
    _G._TEST = true
  end)

  teardown(function()
    _G._TEST = nil
  end)

  it("tests the length of the table", function()
    assert.is.equal(#mymodule._private_element, 3)
  end)

end)
```

Requiring `mymodule` at the top level executes the code from the module at that instance, so when later we define ` _G._TEST = true` within the `setup` function, `mymodule` has already been required and the global `_TEST` is not set.

I don't see any other way than to declare the `mymodule` at the top, and then require it within the `setup` function once the global `_TEST` has been set:

```
local mymodule

describe("Going to test a private element", function()

  setup(function()
    _G._TEST = true
    mymodule = require("mymodule")
  end)

  teardown(function()
    _G._TEST = nil
  end)

  it("tests the length of the table", function()
    assert.is.equal(#mymodule._private_element, 3)
  end)

end)
```

**Comment by DorianGray** [comment]
The way you are doing it there is correct. Docs were out of date. Would you mind making a PR to update them?

**Comment by DorianGray** [comment]
I'd do it myself, but I'd like you to be credited with the contribution

**Comment by bonidjukic** [comment]
@DorianGray, of course, thanks for that! I've created a PR.
