### ISSUE TITLE
A list of tasks as default

### ISSUE THREAD

**Issue by gvela024** [Olivine-Labs/busted#565]
This may or may not be a stupid idea (mine are usually under the `stupid` category), but I want to either:

a. Force users to run a specific task instead of the default task (I have a brute force way of doing this by making it so that `busted` has a heart attack if the user tries to run the default task)

or

b. The default task runs a list of specific tasks.

The reasoning behind this is long and complicated, but in a nutshell, I have several different targets (sort of equivalent to the idea of tasks) in a single repo that are mutually exclusive. I started flipping through all your pages of code but decided to ask if it was a good idea first.

In my perfect little world, a simplified version would look something like:

`.busted`
```Lua
local task1_paths = {
  './path/to/task1/src/?.lua',
  -- ...
}
local task1 = {
  lpath = table.concat(task1_paths, ';'),
  ROOT = { './spec/task1' }
}

local task2_paths = {
  './path/to/task2/src/?.lua',
  -- ...
}
local task2 = {
  lpath = table.concat(task2_paths, ';'),
  ROOT = { './spec/task2' }
}

return {
  default = {
    -- and this is where I'm making stuff up for a list of tasks
    tasks = {
      task1,
      task2
    }
  },
  task1 = task1,
  task2 = task2
}
```

Thoughts? Hate? Love?

**Comment by gvela024** [comment]
I can also change the build process to use `make` and hide all this magic behind that.

**Comment by DorianGray** [comment]
yeah, this feels like what make was created for.

**Comment by gvela024** [comment]
👍

**Comment by gvela024** [comment]
Ended up using make anyway.
