### ISSUE TITLE
Documentation server is down?

### ISSUE THREAD

**Issue by PascalLeMerrer** [Olivine-Labs/busted#568]
Hi

I'm new to busted. 
I can't join the [documentation server](http://olivinelabs.com/busted)
Is it temporary?

**Comment by imolein** [comment]
I think Olivine-Labs doesn't exists anymore, but you can read the documentation here: https://rawgit.com/Olivine-Labs/busted/gh-pages/index.html
Maybe the link in the readme should be replaced.

**Comment by ajacksified** [comment]
it's fixed!

**Comment by ImmoStanke** [comment]
Lovely, thanks for bringing it back 👍 ! Could also fix your certificate configuration?

<img width="628" alt="screen shot 2018-03-13 at 09 14 31" src="https://user-images.githubusercontent.com/14308981/37329707-12af7a32-269f-11e8-82e5-c6b502051b03.png">
<img width="506" alt="screen shot 2018-03-13 at 09 18 07" src="https://user-images.githubusercontent.com/14308981/37329884-993b2290-269f-11e8-9f39-2b1acd95e441.png">
