### ISSUE TITLE
Assert that a function returns multiple values?

### ISSUE THREAD

**Issue by helpermethod** [Olivine-Labs/busted#576]
Hi,

I'm trying to test that a function returns three values, something like

    local host, path, query =  parse_url(url)

But it seems `assert.is_equal` only accepts one argument? What's the correct way to assert that the function returns the correct result? Do I need to write a custom matcher?

Thanks you very much!

**Comment by Tieske** [comment]
Wrap both sides in tables. Something like this

```lua
assert.are.same( { "host-value", "path-value", "query-value" }, { parse_url(url) })
```

**Comment by helpermethod** [comment]
Thank you very much, works perfectly!
