### ISSUE TITLE
assert.spy().was_called_with(...) doesn't provide helpful information on failure

### ISSUE THREAD

**Issue by hsandt** [Olivine-Labs/busted#578]
If assert.spy().was_called_with(...) fails, it just says 

> Function was not called with the arguments

I would like to know which arguments were called instead of the ones expected, just like when testing `assert.are_equal(expected, actual)`.
I had a look at the message format strings and I see where to put %s to insert said arguments, but can't find where I'm supposed to pass those arguments in code so they can be printed.

**Comment by Tieske** [comment]
Iirc this is because the spy might have been invoked a thousand times, but not once with the requested parameters. Hence your request would output a thousands sets of parameters. Also not very helpful.

**Comment by hsandt** [comment]
I'm just having a hard time with understand why was_called_with fails with tables, even with match.ref(), so I came back to this issue.

Indeed, for multiple calls printing will be difficult. But in unit tests it is common to have just a few calls, and I always check for the number of calls before with was_called(x), so I can guarantee that I had only 1 in my case. If the number of calls is higher than 2-3, we could still output "... was called [3] times, but none had matching arguments. The last args passed were: (...)" since we could also imagine the user is particularly interested in the last calls.

If we gather more use cases we can find the output that helps developers for the most common cases. Since the other assertions have some kind of comparison output (even for lists), it would make sense to extend that behavior to the spy assertions.

In the meantime, as a workaround I will inspect the spy history manually with brutal prints.

**Comment by Tieske** [comment]
That logic, of only outputting a limited number of invocation arguments, makes sense. So a PR against Luassert would be nice.
Even if just updating the current output with the number of invocations.

**Comment by qha** [comment]
I have addressed this issue over in: olivine-labs/luassert#165

**Comment by hsandt** [comment]
Looks like the comment parser didn't understand it should close #Y when you put "closes #X and #Y" in your message. So I'm closing this issue manually now.

**Comment by hsandt** [comment]
The PR has been approved, although I don't know when it will get into busted since the last tag 1.8.0 is from Jun 28, 2019 (it's a silent release, the official latest release being 1.7.11, but considering the rockspec mentions luassert >= 1.8.0 I assume it's the one).
