### ISSUE TITLE
olivinelabs.com is down

### ISSUE THREAD

**Issue by Kampfkarren** [Olivine-Labs/busted#579]
![image](https://user-images.githubusercontent.com/3190756/44035748-0e312ae8-9ec5-11e8-9247-9cc41535023c.png)

**Comment by helpermethod** [comment]
Anything new? I'm basically stuck because I can't access the documentation :/.

**Comment by Kampfkarren** [comment]
No, I've been using the wayback machine. @helpermethod

**Comment by ryanford-frontend** [comment]
Maybe this can get hosted on Github Pages? 

In the meantime:

[Wayback version](https://web.archive.org/web/20180215224332/http://olivinelabs.com:80/busted/)

**Comment by ajacksified** [comment]
I'll nuke the CNAME for now, so it falls back to github, until I figure out what's going on.

**Comment by ajacksified** [comment]
http://olivine-labs.github.io/busted/
