### ISSUE TITLE
Creating a new busted release

### ISSUE THREAD

**Issue by mmaarouf** [Olivine-Labs/busted#581]
The latest busted release `v2.0.rc12-1`  is 2 years old. 
Couple of great fixes such have gone into master since such as this [one](https://github.com/Olivine-Labs/busted/commit/db6d8b4be8fd099ab387efeb8232cfd905912abb) .
Could we please get a new release made + new updated rockspec? Would rather not use the `busted-scm-0.rockspec` since master can change.

**Comment by ajacksified** [comment]
2.0.rc13-0

**Comment by Tieske** [comment]
great!
