### ISSUE TITLE
Similar Issue to #169 but those fixes will not work

### ISSUE THREAD

**Issue by davenmir** [Olivine-Labs/busted#590]
![help](https://user-images.githubusercontent.com/35857539/54167154-9709ee80-4425-11e9-9f57-d43f230aa346.PNG)

I have installed all the correct packages and I am still getting the "parse error".

**Comment by Tieske** [comment]
what version of LuaRocks do you use?

**Comment by Tieske** [comment]
also, (considering this: https://github.com/Olivine-Labs/busted/issues/169#issuecomment-24493138 ) do you have multiple Lua installations?

**Comment by davenmir** [comment]
I currently have version 2.0.2 

And I shouldn't have multiple installations. I made sure there were no duplicates.

**Comment by Tieske** [comment]
2.0.2 does not make sense?

Also, this is a LuaRocks issue, so you should better report it there.
