### ISSUE TITLE
newer luarocks makes busted unable to test other lua versions

### ISSUE THREAD

**Issue by edubart** [Olivine-Labs/busted#591]
Since LuaRocks 3 I am unable to use a busted 5.3 lua install to test 5.1 lua codes.

More details and steps to reproduce is on the same issue created at LuaRocks at https://github.com/luarocks/luarocks/issues/980, but I am not sure which project must fix this, so I am also raising the issue here.

**Comment by DorianGray** [comment]
This was fixed in luarocks.
