### ISSUE TITLE
Coverage report on moonscript code has many errors

### ISSUE THREAD

**Issue by Sasszem** [Olivine-Labs/busted#595]
It falsely (and somehow randomly) reports:
 - class declarations
 - function definitions
 - assignments
 - return statements

Here's a few examples:

**Assignment**
```
  2 NataConfig = 
  2     groups: 
  2         all:  {},
  2         velocity: 
  2             filter: {'position', 'velocity'}
  2         despawn:
**0             filter: {'despawnTimer'}
  2     systems: {
  2         require "src.system.DespawnSystem"
  2     }
```

**Function definition & assignment**
```
   class Vec2
**0     new: (x=0, y=0) =>
**0         @x = x
  7         @y = y
```

**Implicit return assignment**
```
  8 @aim = aim
**0 @speed = 50
```

**Comment by Tieske** [comment]
LuaCov is used to track coverage. Since LuaCov is not Moonscript aware, my guess is that that is the culprit here. And if so, then there is no easy fix.

Probably best to document that Coverage is not supported with Moonscript.

**Comment by Sasszem** [comment]
Moon also has a [coverage tool](https://moonscript.org/reference/command_line.html#command-line-tools/moon/code-coverage) - maybe add an option to use it instead of luacov?

**Comment by Tieske** [comment]
PR's are welcome
