### ISSUE TITLE
Link broken on busted 2.0.0 installation via Luarocks

### ISSUE THREAD

**Issue by edubart** [Olivine-Labs/busted#602]
```
luarocks install --local busted
Installing https://luarocks.org/busted-2.0.0-0.rockspec

Error: Error fetching file: Failed downloading https://github.com/Olivine-Labs/busted/archive/v2.0.0-0.tar.gz - v2.0.0-0.tar.gz
```

The link is broken as shown above.

**Comment by hugomg** [comment]
Looks like the rockspec is pointing to `2.0.0-0.tar.gz` but the actual file is at `2.0.0.tar.gz`

**Comment by rubensayshi** [comment]
same issue, was working fine until 2 days ago

**Comment by rubensayshi** [comment]
![image](https://user-images.githubusercontent.com/649160/60400469-5a990480-9b74-11e9-9785-81d3319c854a.png)

looks like a new faulty version was published to laurocks maybe?

**Comment by komapa** [comment]
@ajacksified you gotta fix the release here in Github to have the trailing `-0` as in `v2.0.0-0` in order to fix this.

**Comment by Tieske** [comment]
the proper fix is to update the rockspec. Releases should not include the rockspec revision number (the trailing `-0`)

So remove the `-0` suffixes from the rockspec contents, then rename the rockspec to `-1` (the next revision), and publish it.

Pushing a new tag which includes the `-0` to github will also work, but is the wrong solution.

**Comment by rubensayshi** [comment]
thx for fixing it quickly @Tieske  @ajacksified !
