### ISSUE TITLE
Registering your own functional asserts 

### ISSUE THREAD

**Issue by ktalebian** [Olivine-Labs/busted#611]
I want to register a new `that(variable).*` so I can add my own assertions, for example:

```lua
assert.that(value).contains('foo')
```

I was doing something like:

```lua
local assert = require('luassert')

local _M = {}

local function that(state, arguments)
    return {
        contains = _M.contains(arguments[1])
    }
end

_M.contains = function(arg)
  return function(str)
    return arg:match(str)
  end
end

assert:register('assertion', 'that', that)
```

This does not work; how can I do register a `function`?

**Comment by Tieske** [comment]
That's actually a `luassert` question and not `busted`. But please have a look at the `array` example: https://github.com/Olivine-Labs/luassert/blob/master/src/array.lua . It has exactly what you want.

**Comment by ktalebian** [comment]
Ah thank you!
