### ISSUE TITLE
How to run a `before_each` function on every test

### ISSUE THREAD

**Issue by ktalebian** [Olivine-Labs/busted#613]
I run my tests like `rusty tests/app/init.lua`. For all my tests, I want to have a `before_each` function that runs on all of my tests. I've been able to do this, but I think this is very hacky:

```lua
-- tests/app/init.lua

require 'busted.runner'()

local busted = require 'tests.setup'

busted.describe('init', function()
  describe('a test suite', function() 
     ...
  end)
end)

-- tests/setup.lua 

require 'busted.runner'()
local busted = require('busted')

local mt = getmetatable(busted)
mt.__newindex = nil
local describe = busted.describe

busted.describe = function(title, cb)
    describe(title, function()
        busted.before_each(function()
            -- can run anything here
        end)

        cb()
    end)
end

return busted
```

Is this going to cause any issues? It seems to work fine. Is there a recommended way of doing this?

**Comment by Crack** [comment]
Another possibility:

```lua
require("busted").subscribe({"test", "start"}, function() <your code> end)
```

This can be put in `--helper` script. I'm using this pattern to run some system tests: I set up my environment in `{"suite", "start"}` and tear it down in `{"suite", "end"}`.

**Comment by Tieske** [comment]
nice example @Crack 👍

**Comment by Tieske** [comment]
@ktalebian can we close this?

**Comment by ktalebian** [comment]
Yep.
