### ISSUE TITLE
How to invoke OpenResty library from busted

### ISSUE THREAD

**Issue by kg0r0** [Olivine-Labs/busted#616]
When testing code that includes OpenResty libraries with busted, the following error occurs:
```
attempt to index global 'ngx' (a nil value)
```

I saw the following issues, but it did not solve.
https://github.com/Olivine-Labs/busted/issues/414

I'm sorry, can you tell me the detailed steps?

**Comment by idevz** [comment]
you can using this as  kong dose https://github.com/Kong/kong/blob/master/bin/busted

**Comment by kg0r0** [comment]
Thank you for your reply! I'll try it!
