### ISSUE TITLE
Unable to install dependency (say) - gzip Unexpected End of File

### ISSUE THREAD

**Issue by SquaredCircles** [Olivine-Labs/busted#617]
Summary: when trying to install Busted, I encounter an error from gzip: Unexpected End of File.

System: MacOS 10.14; lua 5.3.5-1; luarocks 3.2.1 (both installed with Homebrew)

STR
1. `luarocks install busted --verbose`
2. Note output: Unexpected End of File

It appears as if the problem is with the call to gunzip. I can download say with curl and extract it successfully with tar, but gunzip throws this error.

[luarocks-verbose-output.txt](https://github.com/Olivine-Labs/busted/files/3837379/luarocks-verbose-output.txt)

**Comment by Tieske** [comment]
that looks like a LuaRocks error to me, not Busted

**Comment by one000mph** [comment]
I am having this problem running `luarocks make` inside the extracted source dir.

**Comment by Tieske** [comment]
even then, it is still a luarocks error.

**Comment by Tieske** [comment]
closing this since it is LR
