### ISSUE TITLE
Busted gives the error 'attempt to call method 'add_flag' (a nil value)'

### ISSUE THREAD

**Issue by Seniru** [Olivine-Labs/busted#618]
I install busted through LuaDist and tried to run busted using the command prompt and I got the following error.

``` bash
/workspace/Module-API-TFM/LuaDist/bin/busted: :25: attempt to call method 'add_flag' (a nil value)
```

**Steps to reproduce**

- I'm using this script for the whole installation process. So you can run these command in your shell

```bash
#pre-installation
echo "$(curl -fksSL https://tinyurl.com/luadist)" | bash
alias lua='LuaDist/bin/lua'
alias luadist='LuaDist/bin/luadist'

#install required libraries
luadist install busted
luadist install luacov

alias busted='LuaDist/bin/busted'
alias luacov='LuaDist/bin/luacov'

```

- Type `busted` in your shell and you may get the error I said

<hr>

**System information**

 -  **OS:**  Linux
- **Environment:** Gitpod
- **cURL version:** curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
- **Lua version:** Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
- **Luadist version:** LuaDist-git 0.2.7
- **Busted:** *Should be the latest version*

**Comment by DorianGray** [comment]
Apologies for the super late response :/

LuaDist is no longer maintained and we have never built a package for it. Unfortunately, we have never supported it. Sorry.
