### ISSUE TITLE
Unable to specify repeat via configuration file

### ISSUE THREAD

**Issue by danlamanna** [Olivine-Labs/busted#624]
Quoting the documentation of "Predefined Busted Tasks":
> You can create a .busted file in the root, which is automatically loaded if it exists. ... You can add any argument available in the CLI (listed above), using the long name (use verbose = true, not v = true).

This doesn't appear to be true since the `--repeat` flag uses a reserved word in Lua. Is there any way of specifying that tests should repeat from the configuration file?

FWIW, my motivation is something like this:
```lua
-- .busted
return {
  exhaustive = {
    repeat = 5,
    shuffle = true,
  },
}
```

Which aptly results in:
```
failed loading config file `.busted`: .busted:3: unexpected symbol near 'repeat'
```

**Comment by Tieske** [comment]
try this:
```lua
-- .busted
return {
  exhaustive = {
    ["repeat"] = 5,
    shuffle = true,
  },
}
```

**Comment by danlamanna** [comment]
Thanks for the basic lua lesson! Sorry for the noise.
