### ISSUE TITLE
Using busted to test something using an FFI lib produces a "cannot change a protected metatable" error when run with luajit

### ISSUE THREAD

**Issue by drhayes** [Olivine-Labs/busted#630]
I'm using an FFI library called brinevector (https://github.com/novemberisms/brinevector). When writing unit tests against code using that library, I get a "cannot change a protected metatable" error when running my tests.

It sure looks like it's because busted loads the module twice, but I'm not sure what's going on. Any insight there? Is this a bug in brinevector or in busted?

**Comment by Tieske** [comment]
please provide some more details, minimal reproduction, and the exact error message and location

**Comment by drhayes** [comment]
Turns out it only happens if I run with luajit!

Here's the repo with the repro: https://github.com/drhayes/busted-repro

I'm unit testing code that will eventually run under luajit, but not sure if I need to run my *tests* with luajit as well, I'll double-check. Also not sure if busted is supposed to run under luajit?

**Comment by Tieske** [comment]
it's another ffi singleton that needs patching.

add `helper.lua` with this code:
```lua

local isJit = (tostring(assert):match('builtin') ~= nil)
if isJit then
  local ffi = require "ffi"
  local ffi_metatype = ffi.metatype
  local metatype_store = {}
  ffi.metatype = function (ct, mt)
    if metatype_store[ct] then
      return metatype_store[ct]
    end
    local success, result, err = pcall(ffi_metatype, ct, mt)
    if not success then
      -- hard error was thrown
      error(result, 2)
    end
    if not result then
      -- soft error was returned
      return result, err
    end
    -- it worked, store and return
    metatype_store[ct] = result
    return result
  end
end
```
And then run the tests using `busted --helper=helper.lua`

**Comment by Tieske** [comment]
Please try the fix in #631 and see whether it fixes the issue.

**Comment by drhayes** [comment]
Using the helper fixed my issue. Not sure how to patch my local busted since I installed it with `luarocks` and I'm a relative lua newbie, but I'll dig around in the next day and learn how to do it.

**Comment by Tieske** [comment]
would be nice if you could test my PR branch;

To clone the repo and install the PR branch do:
```shell
git clone https://github.com/olivine-labs/busted.git
cd busted
git checkout luajit/metatype
luarocks make
```
the final luarocks command will install the version from the checked out repo.

**Comment by Tieske** [comment]
if it works for you, then I'll merge the PR

**Comment by drhayes** [comment]
I'll test it today and get back to you.

**Comment by drhayes** [comment]
It works! The tests that I expected to fail right now fail, no error seen. Thanks for helping me get you the repro.
