### ISSUE TITLE
vscode has no code hints for bursted assets

### ISSUE THREAD

**Issue by ZhouJiaZhi** [Olivine-Labs/busted#647]
There is no code hint when writing assets test, is there any good way?
For example, when I input **assert.a**, I hope vscode can prompt me the words **are**, **are_not**
<img width="844" alt="截屏2020-11-29 21 33 21" src="https://user-images.githubusercontent.com/20750357/100543338-826d2a00-328a-11eb-9e39-d380c46bbb45.png">

**Comment by DorianGray** [comment]
We do not run busted in vscode nor was it designed to support code completion in vscode. Pull requests are welcome!

**Comment by ZhouJiaZhi** [comment]
Hi, @DorianGray 
I wrote a simple vscode code snippet, which can quickly generate busted unit test related code, if you need it, I can push a Pull request
```json
{
	"assert.is_true": {
		"prefix": "assert.is_true",
		"body": [
			"assert.is_true($1);"
		],
		"description": "busted assert"
	},
	"assert.is_not_true": {
		"prefix": "assert.is_not_true",
		"body": [
			"assert.is_not_true($1);"
		],
		"description": "busted assert"
	},
	"assert.is.equal": {
		"prefix": "assert.is.equal",
		"body": [
			"assert.is.equal($1);"
		],
		"description": "busted assert"
	},
	"assert.is.truthy": {
		"prefix": "assert.is.truthy",
		"body": [
			"assert.is.truthy($1);"
		],
		"description": "busted assert"
	},
	"assert.is.falsy": {
		"prefix": "assert.is.falsy",
		"body": [
			"assert.is.falsy($1);"
		],
		"description": "busted assert"
	},
	"assert.is_not.equal": {
		"prefix": "assert.is_not.equal",
		"body": [
			"assert.is_not.equal($1);"
		],
		"description": "busted assert"
	},
	"assert.is.errors": {
		"prefix": "assert.is.errors",
		"body": [
			"assert.is.errors(",
			"\tfunction()",
			"\t\t$1",
			"\tend",
			")"
		],
		"description": "busted assert"
	},
	"assert.is_not.errors": {
		"prefix": "assert.is_not.errors",
		"body": [
			"assert.is_not.errors(",
			"\tfunction()",
			"\t\t$1",
			"\tend",
			")"
		],
		"description": "busted assert"
	},
	"test": {
		"prefix": "test",
		"body": [
			"test(",
			"\t\"$1\",",
			"\tfunction()",
			"\t\t",
			"\tend",
			")"
		],
		"description": "busted assert"
	},
	"describe": {
		"prefix": "describe",
		"body": [
			"describe(",
			"\t\"$1\",",
			"\tfunction()",
			"\t\t",
			"\tend",
			")"
		],
		"description": "busted assert"
	}
}
```
<img width="562" alt="截屏2020-11-30 20 41 02" src="https://user-images.githubusercontent.com/20750357/100611856-f5d77000-334c-11eb-93a7-d898a6f8d6c8.png">
<img width="237" alt="截屏2020-11-30 20 41 17" src="https://user-images.githubusercontent.com/20750357/100611855-f40dac80-334c-11eb-9ab9-8b90c2d609fa.png">
<img width="628" alt="截屏2020-11-30 20 41 37" src="https://user-images.githubusercontent.com/20750357/100611869-f96af700-334c-11eb-8aad-e5443cad7b98.png">
<img width="320" alt="截屏2020-11-30 20 41 46" src="https://user-images.githubusercontent.com/20750357/100611867-f8d26080-334c-11eb-8751-a2b7e91d5a86.png">
<img width="725" alt="截屏2020-11-30 20 43 54" src="https://user-images.githubusercontent.com/20750357/100611859-f7089d00-334c-11eb-8b2c-545db1274833.png">
<img width="483" alt="截屏2020-11-30 20 44 04" src="https://user-images.githubusercontent.com/20750357/100611865-f839ca00-334c-11eb-919e-5619b625172b.png">

**Comment by alerque** [comment]
These functions actually come from the [luassert project](https://github.com/Olivine-Labs/luassert/). I think the correct way to get completion in your editor is to tel your code scanner to look for function definitions in that project's code as well as busted & your own local project.

I do not think code libraries should be responsible for creating completion routines for *any* editor, VScode or otherwise. The list would never end, and some have many different formats they would want the data in depending on the plugin you used. This should be generated by the editor/plugin somewhere feeding it the code libraries being used.

**Comment by ZhouJiaZhi** [comment]
OK, I will try it later
