### ISSUE TITLE
A strange circle will be output after the test run is over

### ISSUE THREAD

**Issue by ZhouJiaZhi** [Olivine-Labs/busted#649]
I wrote a simple unit test. After the test runs, it will output a strange green circle without any other information. I think that every time a unit test is run over, output the name of the unit test and the result of the operation (success, failure, error, pending) would be better
![image](https://user-images.githubusercontent.com/20750357/100544550-910b0f80-3291-11eb-90db-74c45d37907e.png)

**Comment by ZhouJiaZhi** [comment]
Now I know, a green circle represents a successful unit test block, but why not output the name of the unit test block, one line with a green circle and the name of unit test

**Comment by alerque** [comment]
@ZhouJiaZhi Many projects have thousands of test units. If we output a name for each you wouldn't be able to to see an overview in one screen full.

There are however several different output options baked in including ones to be more machine readable (i.e. TAP or JSON), ones to be more pretty (such as the default), more plain, more verbose, etc. You can choose the [output handler](https://olivinelabs.com/busted/#output-handlers) you want to use or even write one of your own.

**Comment by ZhouJiaZhi** [comment]
Thank you, I think 'TAP' is what I need
