### ISSUE TITLE
How to debug busted test case in vscode

### ISSUE THREAD

**Issue by ZhouJiaZhi** [Olivine-Labs/busted#656]
Can someone give me some suggestions

**Comment by alerque** [comment]
This doesn't really seem like enough information to understand what you are trying to accomplish. Also wouldn't this be more of a issue for VSCode than any specific library you are working on with it?

**Comment by ZhouJiaZhi** [comment]
@alerque 
Hi, After installing busted, I can use the busted command to perform unit tests on the command line, but when I use vscode's lua debug plugin, it prompts me that the busted.runner module cannot be found

**Comment by ZhouJiaZhi** [comment]
@aiverson 
Hi, This problem has nothing to do with your busted, it should be a problem with the Lua debug plugin, so I close this issue

**Comment by Tieske** [comment]
> it prompts me that the busted.runner module cannot be found

That probably means you have not set the Lua-path settings correctly, see http://www.thijsschreijer.nl/blog/?p=1025
