### ISSUE TITLE
false vs. nil

### ISSUE THREAD

**Issue by AndreasMatthias** [Olivine-Labs/busted#663]
The following code
``` lua
require('busted.runner')()
x = false
print(x, type(x))
```
outputs
```
nil	nil
```
while the expected result would be
```
false	boolean
```
Installed version of busted:
```
$ busted --version
2.0.0-0
```

**Comment by aki-cat** [comment]
When you write `x = false` what you're really doing is `_G.x = false` (aka declaring a global var `x` in the current environment). If the current environment does not allow writing on `_G`, you won't be able to declare anything in the global scope of that environment.

Use `local x = false` instead.

**Comment by AndreasMatthias** [comment]
OK, understook. Thank you!
