### ISSUE TITLE
could busted exclude all testcase in sub dir?

### ISSUE THREAD

**Issue by ykxpb** [Olivine-Labs/busted#669]
https://github.com/Olivine-Labs/busted/blob/cceb81b25d9f3daf7cb97dc1b630df8a8f72302d/busted/modules/test_file_loader.lua#L14-L36

exclude-pattern only exclude basename.

**Comment by Tieske** [comment]
Not sure what you mean exactly? could you create a testcase that shows the intended behaviour?

**Comment by ykxpb** [comment]
### test file tree
```lua
testdir/foo/a.spec.lua
testdir/b.spec.lua
```

```lua
testdir/foo/a.spec.lua
testdir/b.spec.lua
```

### in .busted config file
["exclude-pattern"] = "foo"

expect a.spec.lua excluded

**Comment by alerque** [comment]
@ykxpb Does tagging your tests not work for your use case?

**Comment by Tieske** [comment]
see code here: https://github.com/Olivine-Labs/busted/commit/52cc01016dbb6a43510613663b0adf29291453d4#diff-9b0f5f2823375d63df9ecc9e211902db4567c0b9b87388a4812a0287f9981071R24
It checks against `path.basename` which is only the [filename(+ext) part](https://lunarmodules.github.io/Penlight/libraries/pl.path.html#basename), so not the full path.
